/**
 * Textos del generador de regex de PoE2 (2026-09-25). El título y la descripción
 * para buscadores están en `i18n.ts` (`seo.poe2.regex`), porque los usa el prerender.
 */
import { useLang } from "../i18n";

const EN = {
  h1: "Path of Exile 2 Regex Generator",
  lede: "Pick what you want to find and what to avoid, copy the result and paste it into the search of your stash, a vendor or the map device (Ctrl+F). Works with the game in English or Spanish.",
  loading: "Loading modifiers…",
  failed: "The modifiers could not be loaded.",
  modes: { waystone: "Waystones", tablet: "Tablets", gear: "Gear & vendors", relic: "Relics" },
  gameLang: "Your game is in:",
  list: "Modifiers",
  out: "Your regex",
  search: "Search a modifier…",
  count: (n: number, t: number) => `${n} of ${t}`,
  want: "Want",
  avoid: "Avoid",
  min: "min",
  copy: "Copy",
  copied: "Copied",
  clear: "Clear",
  link: "Copy link",
  linkCopied: "Link copied",
  empty: "Pick modifiers to build the regex.",
  chars: (n: number) => `${n} / 250 characters`,
  over: "Over 250 characters: the game cuts it off. Remove something.",
  match: "The ones I want:",
  any: "any of them",
  all: "all of them",
  tier: "Tier",
  rarity: "Rarity",
  rarities: { Normal: "Normal", Magic: "Magic", Rare: "Rare" },
  corrupt: "Corruption",
  corr: { any: "Either", yes: "Corrupted", no: "Not corrupted" },
  header: "At least",
  headerKeys: { rarity: "Item rarity %", pack: "Pack size %", drop: "Waystone drop chance %", magic: "Magic monsters %", rare: "Rare monsters %", effect: "Monster effectiveness %" },
  cats: {
    all: "All", life: "Life", mana: "Mana", resistance: "Resistances", speed: "Speed", attack: "Attack", caster: "Spells",
    critical: "Critical", defences: "Defences", attribute: "Attributes", gem: "Skill levels", minion: "Minions",
    elemental: "Elemental", physical: "Physical", chaos: "Chaos",
  },
  tcats: { all: "All", breach: "Breach", delirium: "Delirium", ritual: "Ritual", expedition: "Expedition", abyss: "Abyss", map_boss: "Boss", incursion: "Incursion" },
  selected: "Selected",
  howTitle: "How to use it",
  how: [
    "Open your stash, a vendor or the map device.",
    "Click the search box (or press Ctrl+F) and paste the regex.",
    "Matching items light up; the rest dim.",
  ],
  whatTitle: "What is this for",
  what: [
    "Path of Exile 2 lets you search items with a regular expression: a short formula that lights up only what matches. It is the fastest way to find the waystones worth running, the tablets you want or the boots with movement speed in a vendor.",
    "Each modifier is found by the shortest piece of its text that no other modifier has, taken from the game's own texts in English and Spanish. Numbers allow for the roll range the game shows next to them, like 12(5-20)%.",
    "Choose the language your game is in: the search only understands the texts of your client's language.",
  ],
  fromGame: "Texts from the game, current version. Up to 250 characters, the in-game limit since 0.5.0.",
};

const ES: typeof EN = {
  h1: "Generador de regex de Path of Exile 2",
  lede: "Elegí qué querés encontrar y qué evitar, copiá el resultado y pegalo en la búsqueda del alijo, de un vendedor o del dispositivo de mapas (Ctrl+F). Funciona con el juego en español o en inglés.",
  loading: "Cargando modificadores…",
  failed: "No se pudieron cargar los modificadores.",
  modes: { waystone: "Piedras guía", tablet: "Tablillas", gear: "Equipo y vendedores", relic: "Reliquias" },
  gameLang: "Tu juego está en:",
  list: "Modificadores",
  out: "Tu regex",
  search: "Buscar un modificador…",
  count: (n, t) => `${n} de ${t}`,
  want: "Quiero",
  avoid: "Evitar",
  min: "mín.",
  copy: "Copiar",
  copied: "Copiado",
  clear: "Limpiar",
  link: "Copiar link",
  linkCopied: "Link copiado",
  empty: "Elegí modificadores para armar el regex.",
  chars: (n) => `${n} / 250 caracteres`,
  over: "Se pasa de 250 caracteres: el juego lo corta. Sacá algo.",
  match: "Los que quiero:",
  any: "cualquiera",
  all: "todos",
  tier: "Grado",
  rarity: "Rareza",
  rarities: { Normal: "Normal", Magic: "Mágica", Rare: "Rara" },
  corrupt: "Corrupción",
  corr: { any: "Da igual", yes: "Corrupta", no: "Sin corromper" },
  header: "Como mínimo",
  headerKeys: { rarity: "Rareza de objetos %", pack: "Tamaño de grupos %", drop: "Probabilidad de piedras guía %", magic: "Monstruos mágicos %", rare: "Monstruos raros %", effect: "Efectividad de monstruos %" },
  cats: {
    all: "Todos", life: "Vida", mana: "Maná", resistance: "Resistencias", speed: "Velocidad", attack: "Ataque", caster: "Hechizos",
    critical: "Crítico", defences: "Defensas", attribute: "Atributos", gem: "Niveles de gemas", minion: "Esbirros",
    elemental: "Elemental", physical: "Físico", chaos: "Caos",
  },
  tcats: { all: "Todas", breach: "Fisura", delirium: "Delirio", ritual: "Ritual", expedition: "Expedición", abyss: "Abismo", map_boss: "Jefe", incursion: "Incursión" },
  selected: "Elegidos",
  howTitle: "Cómo se usa",
  how: [
    "Abrí el alijo, un vendedor o el dispositivo de mapas.",
    "Hacé clic en la búsqueda (o Ctrl+F) y pegá el regex.",
    "Lo que cumple se ilumina; lo demás se apaga.",
  ],
  whatTitle: "Para qué sirve",
  what: [
    "Path of Exile 2 deja buscar objetos con una expresión regular: una fórmula corta que ilumina sólo lo que cumple. Es la forma más rápida de encontrar las piedras guía que conviene correr, las tablillas que buscás o las botas con velocidad de movimiento en un vendedor.",
    "Cada modificador se encuentra con el pedazo más corto de su texto que no tiene ningún otro, sacado de los textos del juego en español y en inglés. Los números admiten el rango de la tirada que el juego muestra al lado, como 12(5-20)%.",
    "Elegí el idioma de tu juego: la búsqueda sólo entiende los textos del idioma del cliente.",
  ],
  fromGame: "Textos del juego, versión actual. Hasta 250 caracteres, el límite del juego desde la 0.5.0.",
};

export const useRegexCopy = () => (useLang().lang === "es" ? ES : EN);
