/**
 * Los nombres de los cuartos que llenan botín y que no están en `ROOM_NAMES` (2026-10-02): los de "Dónde aparece" en la
 * ficha de cada objeto (`Hoarderkitchen` no, que no existe en el mapa: ver `loot.py`). Aparte de `rooms.ts` para que el
 * chunk del Mapa no cargue con ellos: los piden, con un `import()` propio y compartido, la pestaña Objetos y la hoja del
 * edificio del Mapa al abrirse (`roomName(raw, lang, LOOT_ROOM_NAMES)`). `[inglés, español rioplatense]`; el test de
 * `zomboidWhereFound` recalcula con los datos que ninguna habitación del botín quede sin nombre.
 */
export const LOOT_ROOM_NAMES: Record<string, [string, string]> = {
  aestheticstorage: ["Beauty salon storage", "Depósito del centro de estética"],
  arenakitchen: ["Arena kitchen", "Cocina del estadio"],
  arenakitchenstorage: ["Arena kitchen storage", "Depósito de la cocina del estadio"],
  armysurplus: ["Army surplus store", "Casa de excedentes militares"],
  backstage: ["Backstage", "Backstage"],
  bakerykitchen: ["Bakery kitchen", "Cocina de la panadería"],
  bandkitchen: ["Band kitchen", "Cocina de la banda"],
  bandlivingroom: ["Band living room", "Sala de la banda"],
  bandmerch: ["Band merch", "Merchandising de la banda"],
  barbecuestore: ["Barbecue store", "Parrillería"],
  barbequestore: ["Barbecue store", "Parrillería"],
  barcountertwiggy: ["Twiggy's bar counter", "Barra de Twiggy"],
  barkitchen: ["Bar kitchen", "Cocina del bar"],
  barstorage: ["Bar storage", "Depósito del bar"],
  baseballgiftstorage: ["Baseball gift storage", "Depósito de regalos de béisbol"],
  baseballgiftstore: ["Baseball gift store", "Tienda de regalos de béisbol"],
  baseballstorage: ["Baseball storage", "Depósito de béisbol"],
  batstorage: ["Bat storage", "Depósito de bates"],
  batterystorage: ["Battery storage", "Depósito de pilas"],
  beergarden: ["Beer garden", "Patio cervecero"],
  blacksmith: ["Blacksmith", "Herrería"],
  bowlingalley: ["Bowling alley", "Bowling"],
  boxing: ["Boxing room", "Sala de boxeo"],
  brewerystorage: ["Brewery storage", "Depósito de la cervecería"],
  burgerdining: ["Burger joint dining room", "Salón de la hamburguesería"],
  burgerkitchen: ["Burger joint kitchen", "Cocina de la hamburguesería"],
  butchery: ["Butchery", "Carnicería"],
  cabinetshipping: ["Cabinet shipping", "Envíos de muebles de cocina"],
  campingstorage: ["Camping store storage", "Depósito de la casa de camping"],
  candystorage: ["Candy store storage", "Depósito de la dulcería"],
  candystore: ["Candy store", "Dulcería"],
  captainoffice: ["Captain's office", "Oficina del capitán"],
  cardealershipoffice: ["Car dealership office", "Oficina de la concesionaria"],
  carpentryworkshop: ["Carpentry workshop", "Carpintería"],
  carsupply: ["Car supply store", "Casa de repuestos"],
  carsupplysport: ["Sport car supply store", "Casa de repuestos deportivos"],
  catfish_dining: ["Catfish restaurant dining room", "Salón del restaurante de bagre"],
  catfish_kitchen: ["Catfish restaurant kitchen", "Cocina del restaurante de bagre"],
  catwalk: ["Catwalk", "Pasarela"],
  cdstore: ["CD store", "Casa de discos"],
  changeroomjockey: ["Jockey changing room", "Vestuario de los jockeys"],
  chinesekitchen: ["Chinese restaurant kitchen", "Cocina del restaurante chino"],
  chineserestaurant: ["Chinese restaurant", "Restaurante chino"],
  classroom_anthro: ["Anthropology classroom", "Aula de antropología"],
  classroom_medieval: ["Medieval history classroom", "Aula de historia medieval"],
  classroom_pioneer: ["Pioneer history classroom", "Aula de historia de los pioneros"],
  classroom_pottery: ["Pottery classroom", "Aula de cerámica"],
  clockrepair: ["Clock repair", "Relojería"],
  clothesstorage: ["Clothing storage", "Depósito de ropa"],
  clothesstorestorage: ["Clothing store storage", "Depósito de la tienda de ropa"],
  clothingstorage: ["Clothing storage", "Depósito de ropa"],
  comicstorage: ["Comic store storage", "Depósito de la casa de historietas"],
  comicstore: ["Comic store", "Casa de historietas"],
  controlroom: ["Control room", "Sala de control"],
  cornerstorecounter: ["Corner store counter", "Mostrador del almacén de barrio"],
  cornerstorestorage: ["Corner store storage", "Depósito del almacén de barrio"],
  coroneroffice: ["Coroner's office", "Oficina del forense"],
  cybercafe: ["Cyber café", "Cibercafé"],
  dartgame: ["Dart game", "Juego de dardos"],
  daycare: ["Daycare", "Guardería"],
  deepfry_kitchen: ["Deep fry kitchen", "Cocina de frituras"],
  dentiststorage: ["Dentist storage", "Depósito del dentista"],
  departmentstorage: ["Department store storage", "Depósito de la tienda por departamentos"],
  derelict_steelfactory: ["Derelict steel factory", "Acería abandonada"],
  detectiveoffice: ["Detective office", "Oficina de detectives"],
  dinerbackroom: ["Diner back room", "Trastienda del diner"],
  dinercounter: ["Diner counter", "Mostrador del diner"],
  dinerkitchen: ["Diner kitchen", "Cocina del diner"],
  dining_crepe: ["Crêperie dining room", "Salón de la crepería"],
  dogfoodshipping: ["Dog food shipping", "Envíos de alimento para perros"],
  dogfoodstorage: ["Dog food storage", "Depósito de alimento para perros"],
  donut_dining: ["Donut shop dining room", "Salón de la tienda de donas"],
  donut_kitchen: ["Donut shop kitchen", "Cocina de la tienda de donas"],
  donut_kitchenstorage: ["Donut shop kitchen storage", "Depósito de la cocina de donas"],
  druglab: ["Drug lab", "Laboratorio de drogas"],
  drugshack: ["Drug shack", "Casilla de drogas"],
  duckshootgame: ["Duck shooting game", "Juego de tiro a los patos"],
  eggstorage: ["Egg storage", "Depósito de huevos"],
  electronicsstorage: ["Electronics store storage", "Depósito de la casa de electrónica"],
  elementaryhall: ["Elementary school hall", "Pasillo de la escuela primaria"],
  elementaryschool: ["Elementary school", "Escuela primaria"],
  evidenceroom: ["Evidence room", "Sala de evidencias"],
  factorystorage: ["Factory storage", "Depósito de la fábrica"],
  fishchipskitchen: ["Fish and chips kitchen", "Cocina de la casa de pescado y papas"],
  fishing: ["Fishing store", "Casa de pesca"],
  fishingstorage: ["Fishing store storage", "Depósito de la casa de pesca"],
  florist: ["Florist", "Florería"],
  furnitureshowroom: ["Furniture showroom", "Salón de exhibición de muebles"],
  furniturestorage: ["Furniture store storage", "Depósito de la mueblería"],
  furnitureworkshop: ["Furniture workshop", "Taller de muebles"],
  garage_ranger: ["Ranger garage", "Garaje de los guardabosques"],
  gasstorage: ["Gas station storage", "Depósito de la estación de servicio"],
  generalstorestorage: ["General store storage", "Depósito del almacén de ramos generales"],
  giftstorage: ["Gift store storage", "Depósito de la regalería"],
  gigamartkitchen: ["GigaMart kitchen", "Cocina del GigaMart"],
  glassesstore: ["Glasses store", "Tienda de anteojos"],
  glassmakingworkshop: ["Glassmaking workshop", "Taller de vidrio"],
  golffactory: ["Golf factory", "Fábrica de palos de golf"],
  golfshipping: ["Golf shipping", "Envíos de golf"],
  golfstore: ["Golf store", "Tienda de golf"],
  gunstorestorage: ["Gun store storage", "Depósito de la armería"],
  gymstorage: ["Gym storage", "Depósito del gimnasio"],
  hairdresser: ["Hairdresser", "Peluquería"],
  homecinema: ["Home cinema", "Sala de cine"],
  hoopgame: ["Hoop game", "Juego del aro de básquet"],
  hospitalhallway: ["Hospital hallway", "Pasillo del hospital"],
  hotdogstand: ["Hot dog stand", "Puesto de panchos"],
  hunting: ["Hunting store", "Casa de caza"],
  icecream: ["Ice cream shop", "Heladería"],
  icecreamkitchen: ["Ice cream shop kitchen", "Cocina de la heladería"],
  icecreamstand: ["Ice cream stand", "Puesto de helados"],
  interrogationroom: ["Interrogation room", "Sala de interrogatorios"],
  italiankitchen: ["Italian restaurant kitchen", "Cocina del restaurante italiano"],
  italianrestaurant: ["Italian restaurant", "Restaurante italiano"],
  jackiejayeoffice: ["Jackie Jaye's office", "Oficina de Jackie Jaye"],
  jackiejayestudio: ["Jackie Jaye's studio", "Estudio de Jackie Jaye"],
  jayschicken_dining: ["Jay's Chicken dining room", "Salón de Jay's Chicken"],
  jayschicken_kitchen: ["Jay's Chicken kitchen", "Cocina de Jay's Chicken"],
  jerkycoldroom: ["Jerky factory cold room", "Cámara fría de la fábrica de charqui"],
  jerkyfactory: ["Jerky factory", "Fábrica de charqui"],
  jerkyshipping: ["Jerky shipping", "Envíos de charqui"],
  jerkysmoker: ["Jerky smokehouse", "Ahumadero de charqui"],
  jewelrystorage: ["Jewelry store storage", "Depósito de la joyería"],
  joanstudio: ["Joan's studio", "Estudio de Joan"],
  judgematthassset: ["Judge Matt Hass bar", "Bar Judge Matt Hass"],
  juicestand: ["Juice stand", "Puesto de jugos"],
  kitchen_crepe: ["Crêperie kitchen", "Cocina de la crepería"],
  kitchenwares: ["Kitchenware store", "Bazar de cocina"],
  knappingworkshop: ["Knapping workshop", "Taller de talla de piedra"],
  knifeshipping: ["Knife shipping", "Envíos de cuchillos"],
  knoxbutcher: ["Knox butcher", "Carnicería de Knox"],
  laundryshirts: ["Shirt laundry", "Lavadero de camisas"],
  laundrysuits: ["Suit laundry", "Lavadero de trajes"],
  leatherclothesstore: ["Leather clothing store", "Tienda de ropa de cuero"],
  leatherworkshop: ["Leather workshop", "Taller de cuero"],
  loggingfactory: ["Logging factory", "Fábrica maderera"],
  loggingwarehouse: ["Logging warehouse", "Depósito maderero"],
  lostandfound: ["Lost and found", "Objetos perdidos"],
  mannequinfactory: ["Mannequin factory", "Fábrica de maniquíes"],
  mannequinpainting: ["Mannequin painting", "Pintura de maniquíes"],
  masonrystore: ["Masonry store", "Corralón de materiales"],
  mayorwestpointoffice: ["West Point mayor's office", "Oficina del intendente de West Point"],
  metalfabrication: ["Metal fabrication", "Fabricación de metal"],
  metalshipping: ["Metal shipping", "Envíos de metal"],
  mexicankitchen: ["Mexican restaurant kitchen", "Cocina del restaurante mexicano"],
  movierental: ["Movie rental", "Videoclub"],
  musicschool: ["Music school", "Escuela de música"],
  newspaperprint_herald: ["Herald print shop", "Imprenta del Herald"],
  newspapershipping_herald: ["Herald shipping", "Envíos del Herald"],
  newspaperstorage_herald: ["Herald storage", "Depósito del Herald"],
  nolansoffice: ["Nolan's office", "Oficina de Nolan"],
  officechurch: ["Church office", "Oficina de la iglesia"],
  oldarmy: ["Old army building", "Edificio militar viejo"],
  oldmedical: ["Old medical building", "Consultorio viejo"],
  outdoorsupply: ["Outdoor supply store", "Casa de artículos para el aire libre"],
  outdoorsupply_storage: ["Outdoor supply storage", "Depósito de artículos para el aire libre"],
  paintershop: ["Paint store", "Pinturería"],
  pawnshopcooking: ["Pawnshop kitchen", "Cocina de la casa de empeños"],
  pawnshopoffice: ["Pawnshop office", "Oficina de la casa de empeños"],
  pawnshopstorage: ["Pawnshop storage", "Depósito de la casa de empeños"],
  petstore: ["Pet store", "Tienda de mascotas"],
  pharmacystorage: ["Pharmacy storage", "Depósito de la farmacia"],
  photoroom: ["Photo room", "Sala de fotografía"],
  pizzakitchen: ["Pizzeria kitchen", "Cocina de la pizzería"],
  pizzawhirledcounter: ["Pizza Whirled counter", "Mostrador de Pizza Whirled"],
  plazastore: ["Strip mall store", "Local de la galería comercial"],
  policearchive: ["Police archive", "Archivo de la policía"],
  policegarage: ["Police garage", "Garaje de la policía"],
  policegunstorage: ["Police gun storage", "Depósito de armas de la policía"],
  policelibrary: ["Police library", "Biblioteca de la policía"],
  policeoutfitstorage: ["Police outfit storage", "Depósito de uniformes de la policía"],
  policeswat: ["SWAT room", "Sala del SWAT"],
  pool: ["Pool", "Pileta"],
  post: ["Post office", "Correo"],
  poststorage: ["Post office storage", "Depósito del correo"],
  potatostorage: ["Potato storage", "Depósito de papas"],
  potteryworkshop: ["Pottery workshop", "Taller de cerámica"],
  prisonerbelongings: ["Prisoner belongings", "Pertenencias de los presos"],
  prisonlocker: ["Prison lockers", "Lockers de la cárcel"],
  prisonstorage: ["Prison storage", "Depósito de la cárcel"],
  radioshipping: ["Radio shipping", "Envíos de radios"],
  radiostorage: ["Radio storage", "Depósito de radios"],
  railroadrepair: ["Railroad repair", "Taller ferroviario"],
  railroadstorage: ["Railroad storage", "Depósito ferroviario"],
  rangerhall: ["Ranger hall", "Hall de los guardabosques"],
  rangerlocker: ["Ranger lockers", "Lockers de los guardabosques"],
  rangerstorage: ["Ranger storage", "Depósito de los guardabosques"],
  recreation: ["Recreation room", "Sala de recreación"],
  restaurantkitchen_fancy: ["Fancy restaurant kitchen", "Cocina del restaurante elegante"],
  ringtossgame: ["Ring toss game", "Juego de los aros"],
  schoolgymstorage: ["School gym storage", "Depósito del gimnasio de la escuela"],
  schoollab: ["School lab", "Laboratorio de la escuela"],
  schoolstorage: ["School storage", "Depósito de la escuela"],
  seafoodkitchen: ["Seafood restaurant kitchen", "Cocina de la marisquería"],
  secondaryhall: ["High school hall", "Pasillo de la secundaria"],
  sewingstorage: ["Sewing store storage", "Depósito de la mercería"],
  sherrif: ["Sheriff's office", "Oficina del sheriff"],
  smokingroom: ["Smoking room", "Sala de fumadores"],
  spiffo_dining: ["Spiffo's dining room", "Salón de Spiffo's"],
  spiffoskitchen: ["Spiffo's kitchen", "Cocina de Spiffo's"],
  spiffosstorage: ["Spiffo's storage", "Depósito de Spiffo's"],
  sportstorage: ["Sports storage", "Depósito de artículos deportivos"],
  sportstore: ["Sports store", "Tienda de deportes"],
  stripclub: ["Strip club", "Cabaret"],
  stripclubvip: ["Strip club VIP room", "Sala VIP del cabaret"],
  studio: ["Studio", "Estudio"],
  sushidining: ["Sushi dining room", "Salón del sushi"],
  sushikitchen: ["Sushi kitchen", "Cocina del sushi"],
  swatlocker: ["SWAT lockers", "Lockers del SWAT"],
  tacokitchen: ["Taco restaurant kitchen", "Cocina de la taquería"],
  tailoringworkshop: ["Tailoring workshop", "Taller de sastrería"],
  technical: ["Technical room", "Sala técnica"],
  theatrekitchen: ["Theater kitchen", "Cocina del cine"],
  theatrestorage: ["Theater storage", "Depósito del cine"],
  throwgame: ["Throwing game", "Juego de lanzamiento"],
  tobaccostorage: ["Tobacco store storage", "Depósito de la tabaquería"],
  tobaccostore: ["Tobacco store", "Tabaquería"],
  toolstorestorage: ["Hardware store storage", "Depósito de la ferretería"],
  toystorestorage: ["Toy store storage", "Depósito de la juguetería"],
  universitylibrary: ["University library", "Biblioteca de la universidad"],
  universitystorage: ["University storage", "Depósito de la universidad"],
  vacated: ["Vacated space", "Local desocupado"],
  viplounge: ["VIP lounge", "Sala VIP"],
  waterstorage: ["Water storage", "Depósito de agua"],
  weddingstoredress: ["Wedding dresses", "Vestidos de novia"],
  weddingstorestorage: ["Wedding store storage", "Depósito de la tienda de novias"],
  weddingstoresuit: ["Wedding suits", "Trajes para la boda"],
  weldingstorage: ["Welding storage", "Depósito de soldadura"],
  weldingworkshop: ["Welding workshop", "Taller de soldadura"],
  westerndining: ["Western restaurant dining room", "Salón del restaurante western"],
  westernkitchen: ["Western restaurant kitchen", "Cocina del restaurante western"],
  whiskeybottling: ["Whiskey bottling plant", "Embotelladora de whisky"],
  whittlerworkshop: ["Whittling workshop", "Taller de tallado en madera"],
  woodcraftset: ["Woodcraft workshop", "Carpintería artesanal"],
  zippeestorage: ["Zippee storage", "Depósito de Zippee"],
  zippeestore: ["Zippee store", "Tienda Zippee"],
};

export default LOOT_ROOM_NAMES;
