/**
 * Los nombres de las zonas de las capas del Mapa de Project Zomboid (2026-09-30, Task 3), en inglés y español: lo que
 * dice cada zona al tocarla ("Vehículos: policía") y el texto que va adentro. El juego las nombra con ids internos
 * ("rtrafficjamw", "VariousFoodMarket", "notchickenlarge") sin traducción, así que acá está lo que dice cada una,
 * escrito a mano. Los autos y los zombis van por la tabla del juego que usa la zona, en minúsculas; las historias, por
 * el nombre tal cual (ver `layers.ts`: sólo se nombra lo que el juego define). `zomboidMapLayers.test.ts` cuida que todo
 * lo del mapa esté.
 *
 * Aparte de `copy.ts` porque sólo las usa el visor (`overlays.ts`): así viajan en su chunk, que se pide al montarse, y no
 * en el de la pestaña, que tiene que llegar rápido para el primer dibujo. La recolección se nombra con los textos de la
 * leyenda (`copy.ts`), que la página ya tiene.
 */
import type { Lang } from "../../i18n";
import { MAP_COPY } from "./copy";

/**
 * Los edificios con nombre propio que separados en palabras no quedan bien ("BinkysFarm" → "Binky's Farm"). Son
 * nombres propios: iguales en los dos idiomas. Los demás ("KnoxBank") se separan solos.
 */
export const BUILDING_NAMES: Record<string, string> = {
  binkysfarm: "Binky's Farm",
  benscabin: "Ben's Cabin",
  nolansusedcars: "Nolan's Used Cars",
  greenes: "Greene's",
  smokeys: "Smokey's",
  hsmithattorney: "H. Smith, Attorney",
  massgenfacco: "Mass Genfac Co.",
  ustoreit: "U-Store-It",
  crossroadsmall: "Crossroads Mall",
};

const EN = {
  /** Lo que dice una zona al tocarla o al pasar el mouse. */
  zone: {
    vehicles: (type: string) => `Vehicles: ${type}`,
    forage: (kind: string) => `Foraging: ${kind}`,
    animals: (what: string) => `Animals: ${what}`,
    basement: "Possible basement (random each run)",
    zombies: (type: string) => `Zombies: ${type}`,
    story: (what: string) => `Story: ${what}`,
    loot: { rich: "Rich loot", poor: "Poor loot" },
    floor: (label: string, floor: string) => `${label} · floor ${floor}`,
    /** Un lugar para autos con un tipo que el juego no define: ahí no aparece ninguno. */
    noVehicles: "no cars spawn here",
  },
  vehicleTypes: {
    "": "any car",
    good: "good cars",
    medium: "average cars",
    bad: "beat-up cars",
    sport: "sports cars",
    junkyard: "wrecks",
    normalburnt: "burnt wrecks",
    specialburnt: "burnt service vehicles",
    farm: "farm vehicles",
    trafficjam: "traffic jam",
    /** Los "rtrafficjam…": el juego los arma una de cada diez veces (Rand.Next(100) < 10 en IsoChunk). */
    rtrafficjam: "sometimes a traffic jam",
    trailerpark: "junk pile",
    police: "police",
    prison: "prison",
    fire: "fire department",
    ranger: "park rangers",
    ambulance: "ambulances",
    mccoy: "McCoy Logging trucks",
    carpenter: "carpenter vans",
    postal: "mail trucks",
    spiffo: "Spiffo's vans",
    radio: "radio station vans",
    fossoil: "Fossoil trucks",
    scarlet: "Scarlet vans",
    massgenfac: "Mass Genfac Co. vans",
    transit: "public transit",
    network3: "3 Network TV vans",
    kyheralds: "KY Herald vans",
    lectromax: "LectroMax vans",
    knoxdisti: "Knox Distillery trucks",
    advertising: "advertising vans",
    airportshuttle: "airport shuttles",
    airportservice: "airport service vehicles",
    racecar: "race cars",
  } as Record<string, string>,
  zombieTypes: {
    "": "mixed",
    offices: "office workers",
    factory: "factory workers",
    restaurant: "restaurant staff",
    constructionsite: "construction workers",
    police: "police officers",
    dinner: "diner staff",
    bar: "bar crowd",
    doctor: "doctors and nurses",
    prison: "inmates and guards",
    carrepair: "mechanics",
    swimmingpool: "swimmers",
    variousfoodmarket: "market staff",
    streetsports: "joggers and athletes",
    farm: "farmers",
    firedept: "firefighters",
    school: "students and teachers",
    army: "soldiers",
    bank: "bank staff",
    spiffo: "Spiffo's staff",
    secretlab: "lab scientists",
    survivalist: "survivalists and hunters",
    hotelrich: "rich hotel guests",
    university: "college students",
    pizzawhirled: "Pizza Whirled staff",
    pharmacist: "pharmacists",
    fancyhotel: "fancy hotel staff",
    gas2go: "Gas 2 Go staff",
    fossoil: "Fossoil staff",
    gigamart: "Gigamart staff",
    streetpoor: "poor townsfolk",
    farmingstore: "farm store staff",
    coffeeshop: "coffee shop crowd",
    countryclub: "golfers and club members",
    rich: "wealthy folks",
    pileocrepe: "Pile o' Crepe staff",
    seahorse: "Seahorse waiters",
    athletic: "athletes",
    mob: "mobsters",
    baseballfan: "baseball fans",
    wedding: "wedding guests",
    jays: "Jay's Chicken staff",
    young: "clubbers and goths",
    rocker: "rockers",
    trailerpark: "trailer park folks",
    shelter: "homeless and punks",
    nursinghome: "nursing home residents",
    nightclub: "clubbers",
    bowling: "bowlers",
    lasertag: "laser tag players",
    spa: "spa guests",
    thundergas: "Thunder Gas staff",
    cultists: "cultists",
    stripclub: "strip club crowd",
    theatre: "theater crowd",
    boxing: "boxers",
    beach: "beachgoers",
    baseball: "baseball players",
    mccoys: "McCoy loggers",
    tennis: "tennis players",
    cornmaze: "corn maze visitors",
    cowboy: "Wild West costumes",
    secretbase: "secret base",
    pony: "jockeys",
  } as Record<string, string>,
  /**
   * Por el nombre tal cual de la zona (el juego compara con mayúsculas). Sólo los que el juego usa (`ZoneDefs.stories`): una zona
   * con otro nombre no arma ninguna historia y el visor no la muestra.
   */
  stories: {
    Forest: "a random scene in the woods",
    Lake: "a random scene by the lake",
    Beach: "a random scene on the beach",
    Baseball: "a baseball game",
    MusicFest: "a music festival",
    MusicFestStage: "the festival stage",
    KirstyKormick: "Kirsty Cormick",
    FrankHemingway: "Frank Hemingway",
    SirTwiggy: "Sir Twiggy",
  } as Record<string, string>,
  ranch: {
    species: {
      cow: "cows",
      pig: "pigs",
      sheep: "sheep",
      chicken: "chickens",
      turkey: "turkeys",
      rabbit: "rabbits",
      notchicken: "cows, sheep or pigs",
      poultry: "chickens or turkeys",
      pigonlyone: "a single pig",
    } as Record<string, string>,
    small: "small pen",
    large: "big pen",
  },
  /** Los tipos de recolección, como los nombra la leyenda. */
  forage: MAP_COPY.en.layers.forage,
};

export type ZoneNames = typeof EN;

const ES: ZoneNames = {
  zone: {
    vehicles: (type) => `Vehículos: ${type}`,
    forage: (kind) => `Recolección: ${kind}`,
    animals: (what) => `Animales: ${what}`,
    basement: "Sótano posible (al azar en cada partida)",
    zombies: (type) => `Zombis: ${type}`,
    story: (what) => `Historia: ${what}`,
    loot: { rich: "Botín rico", poor: "Botín pobre" },
    floor: (label, floor) => `${label} · piso ${floor}`,
    noVehicles: "acá no aparecen autos",
  },
  vehicleTypes: {
    "": "cualquier auto",
    good: "autos buenos",
    medium: "autos comunes",
    bad: "autos viejos",
    sport: "autos deportivos",
    junkyard: "desarmadero",
    normalburnt: "autos quemados",
    specialburnt: "vehículos de servicio quemados",
    farm: "vehículos de campo",
    trafficjam: "embotellamiento",
    rtrafficjam: "a veces un embotellamiento",
    trailerpark: "pila de chatarra",
    police: "policía",
    prison: "cárcel",
    fire: "bomberos",
    ranger: "guardaparques",
    ambulance: "ambulancias",
    mccoy: "camiones de la maderera McCoy",
    carpenter: "camionetas de carpintero",
    postal: "camionetas del correo",
    spiffo: "camionetas de Spiffo's",
    radio: "camionetas de la radio",
    fossoil: "camionetas de Fossoil",
    scarlet: "camionetas de Scarlet",
    massgenfac: "camionetas de Mass Genfac Co.",
    transit: "transporte público",
    network3: "camionetas del canal 3 Network",
    kyheralds: "camionetas del KY Herald",
    lectromax: "camionetas de LectroMax",
    knoxdisti: "camiones de la destilería Knox",
    advertising: "camionetas de publicidad",
    airportshuttle: "traslados del aeropuerto",
    airportservice: "vehículos de servicio del aeropuerto",
    racecar: "autos de carrera",
  },
  zombieTypes: {
    "": "variados",
    offices: "oficinistas",
    factory: "obreros de fábrica",
    restaurant: "personal de restaurante",
    constructionsite: "obreros de la construcción",
    police: "policías",
    dinner: "mozos de diner",
    bar: "gente de bar",
    doctor: "médicos y enfermeros",
    prison: "presos y guardias",
    carrepair: "mecánicos",
    swimmingpool: "bañistas",
    variousfoodmarket: "empleados de mercado",
    streetsports: "corredores y deportistas",
    farm: "granjeros",
    firedept: "bomberos",
    school: "alumnos y maestros",
    army: "soldados",
    bank: "empleados de banco",
    spiffo: "empleados de Spiffo's",
    secretlab: "científicos del laboratorio",
    survivalist: "supervivencialistas y cazadores",
    hotelrich: "huéspedes de hotel caro",
    university: "universitarios",
    pizzawhirled: "empleados de Pizza Whirled",
    pharmacist: "farmacéuticos",
    fancyhotel: "personal de hotel de lujo",
    gas2go: "empleados de Gas 2 Go",
    fossoil: "empleados de Fossoil",
    gigamart: "empleados de Gigamart",
    streetpoor: "gente humilde",
    farmingstore: "empleados de la agroveterinaria",
    coffeeshop: "gente de cafetería",
    countryclub: "golfistas y socios del club",
    rich: "gente adinerada",
    pileocrepe: "empleados de Pile o' Crepe",
    seahorse: "mozos del Seahorse",
    athletic: "atletas",
    mob: "mafiosos",
    baseballfan: "hinchas de béisbol",
    wedding: "invitados a una boda",
    jays: "empleados de Jay's Chicken",
    young: "chicos de boliche y góticos",
    rocker: "rockeros",
    trailerpark: "vecinos de casas rodantes",
    shelter: "gente sin techo y punks",
    nursinghome: "abuelos del geriátrico",
    nightclub: "gente de boliche",
    bowling: "bowling",
    lasertag: "jugadores de laser tag",
    spa: "clientes del spa",
    thundergas: "empleados de Thunder Gas",
    cultists: "sectarios",
    stripclub: "cabaret",
    theatre: "público del teatro",
    boxing: "boxeadores",
    beach: "gente de playa",
    baseball: "jugadores de béisbol",
    mccoys: "leñadores de McCoy",
    tennis: "tenistas",
    cornmaze: "visitantes del laberinto de maíz",
    cowboy: "ropa de vaquero",
    secretbase: "base secreta",
    pony: "jockeys",
  },
  stories: {
    Forest: "una escena al azar en el bosque",
    Lake: "una escena al azar junto al lago",
    Beach: "una escena al azar en la playa",
    Baseball: "un partido de béisbol",
    MusicFest: "un festival de música",
    MusicFestStage: "el escenario del festival",
    KirstyKormick: "Kirsty Cormick",
    FrankHemingway: "Frank Hemingway",
    SirTwiggy: "Sir Twiggy",
  },
  ranch: {
    species: {
      cow: "vacas",
      pig: "chanchos",
      sheep: "ovejas",
      chicken: "gallinas",
      turkey: "pavos",
      rabbit: "conejos",
      notchicken: "vacas, ovejas o chanchos",
      poultry: "gallinas o pavos",
      pigonlyone: "un solo chancho",
    },
    small: "corral chico",
    large: "corral grande",
  },
  forage: MAP_COPY.es.layers.forage,
};

export const ZONE_NAMES: Record<Lang, ZoneNames> = { en: EN, es: ES };
