/**
 * Textos de la sección Diablo II: Resurrected (2026-09-29).
 *
 * Aparte de `i18n.ts`, como `valheimCopy.ts`: sólo los usa esta sección. Los
 * nombres del juego (runas, ítems, habilidades, clases) NO están acá: vienen en
 * los datos de la sección en los dos idiomas, así que siempre son los oficiales.
 * El español es el de Latinoamérica (`esMX`).
 */
import { useLang } from "./i18n";

export { SEASON } from "./d2r/season";

/**
 * Las pestañas de la sección, en el orden en que se dibujan: primero las que
 * existen (`LIVE`), después las que vienen, apagadas y sin enlace.
 */
export const D2R_TABS = ["home", "runes", "runewords", "uniques", "sets", "bases", "cube", "classes", "terror-zones", "breakpoints", "drops", "planner", "grail", "patches"] as const;
export type D2rTabKey = (typeof D2R_TABS)[number];
export const D2R_LIVE: D2rTabKey[] = ["home", "runes", "runewords", "uniques", "sets", "bases", "cube", "classes", "terror-zones", "breakpoints", "drops", "planner", "grail", "patches"];
/** Las pestañas que todavía se están completando: llevan la etiqueta "Beta" (ZoTaD, 2026-09-30). */
export const D2R_BETA: D2rTabKey[] = ["classes"];

const EN = {
  seo: {
    title: "Diablo 2 Resurrected Runes, Runewords & Uniques (D2R) | Vestigo",
    description:
      "All 33 Diablo II: Resurrected runes with their level and the runewords they make, plus everything that drops in Sanctuary: uniques, sets, bases and the Horadric Cube.",
    runes: { title: "Diablo 2 Resurrected Runes: All 33 Runes and Their Effects | Vestigo", description: "Every rune in Diablo II: Resurrected, from El to Zod: what it gives in weapons, armor and shields, its required level and the runewords it makes." },
    rune: (name: string) => ({ title: `${name} in Diablo 2 Resurrected: Effects and Runewords | Vestigo`, description: `${name} in Diablo II: Resurrected: what it gives in weapons, armor and shields, its required level and every runeword that uses it.` }),
    runewords: { title: "Diablo 2 Resurrected Runewords: Full List and Calculator | Vestigo", description: "All Diablo II: Resurrected runewords with their runes in order, the bases they go into and their stats. Tick the runes you have and see what you can make." },
    runeword: (name: string) => ({ title: `${name} Runeword in Diablo 2 Resurrected (D2R) | Vestigo`, description: `${name} runeword in Diablo II: Resurrected: runes in order, the bases it goes into, required level and every stat.` }),
    uniques: { title: "Diablo 2 Resurrected Unique Items: Full List | Vestigo", description: "Every unique item that can drop in Diablo II: Resurrected, by category, with its base, required level and stats." },
    unique: (name: string) => ({ title: `${name} – Diablo 2 Resurrected Unique | Vestigo`, description: `${name} in Diablo II: Resurrected: base item, required level and every stat with its range.` }),
    sets: { title: "Diablo 2 Resurrected Set Items: All Sets and Bonuses | Vestigo", description: "Every set in Diablo II: Resurrected with all its items, the bonuses for each number of pieces and the full set bonus." },
    set: (name: string) => ({ title: `${name} Set – Diablo 2 Resurrected | Vestigo`, description: `${name} in Diablo II: Resurrected: every item of the set, its stats and the bonuses for 2, 3 and all pieces.` }),
    bases: { title: "Diablo 2 Resurrected Item Bases: Weapons and Armor | Vestigo", description: "Every weapon and armor base in Diablo II: Resurrected: normal, exceptional and elite, with defense, damage, requirements and maximum sockets." },
    classes: { title: "Diablo 2 Resurrected Classes and Skill Trees | Vestigo", description: "The eight Diablo II: Resurrected classes, Warlock included, with their three skill trees: every skill, its required level, what it needs first and what it does." },
    patches: { title: "Diablo 2 Resurrected Patch Notes Explained | Vestigo", description: "Every Diablo II: Resurrected patch of the Reign of the Warlock era, summarized: what changed, what it means for your character and the link to the official notes." },
    patch: (name: string) => ({ title: `Diablo 2 Resurrected Patch ${name}: What Changed | Vestigo`, description: `Diablo II: Resurrected patch ${name} summarized: every important change and what it means for your character.` }),
    cube: { title: "Diablo 2 Resurrected Horadric Cube Recipes: Full List | Vestigo", description: "Every Horadric Cube recipe in Diablo II: Resurrected: rune and gem upgrades, crafted items with their stats, sockets, upgrades, portals and more." },
    breakpoints: { title: "Diablo 2 Resurrected Breakpoints: FCR, FHR and FBR for Every Class (Warlock Included) | Vestigo", description: "Faster cast rate, faster hit recovery and faster block rate breakpoints for every Diablo II: Resurrected class and weapon type, Warlock included. Enter yours and see how far the next one is." },
    "terror-zones": { title: "Diablo 2 Resurrected Terror Zones: List, Levels and Immunities | Vestigo", description: "All 34 Diablo II: Resurrected Terror Zones by act: their areas, waypoint, monster level on each difficulty, Hell Heralds and the immunities of every monster in Hell." },
    cls: (name: string) => ({ title: `${name} Skill Tree – Diablo 2 Resurrected | Vestigo`, description: `Every ${name} skill in Diablo II: Resurrected, tree by tree: required level, prerequisites and what each skill does.` }),
    grail: { title: "D2R Holy Grail Tracker: Uniques, Sets, Runewords and Runes | Vestigo", description: "Track your Diablo II: Resurrected Holy Grail: tick every unique, set item, runeword and rune you find, see what you are missing with its recipe and share your progress with a link. Free, no account." },
    drops: { title: "D2R Drop Calculator: Where to Farm Any Item (Terror Zones Included) | Vestigo", description: "Where to farm any Diablo II: Resurrected unique, set item, rune or base: the best bosses and areas with their exact chance, with your magic find and players, Terror Zones and Heralds included. Plus what every boss drops and a loot simulator." },
    dropsSource: (name: string) => ({ title: `${name} Drops in Diablo 2 Resurrected: Runes, Uniques and Sets | Vestigo`, description: `Every rune, unique and set item ${name} can drop in Diablo II: Resurrected, with its exact chance per kill in Normal, Nightmare and Hell.` }),
    planner: { title: "Diablo 2 Resurrected Gear Planner: Total Stats for Your Build | Vestigo", description: "Equip uniques, sets and runewords on your Diablo II: Resurrected character and see the total resistances, FCR, FHR, run speed, magic find and skills. Free, share it with a link." },
  },
  tabs: {
    home: "Home", runes: "Runes", runewords: "Runewords", uniques: "Uniques", sets: "Sets", bases: "Bases", planner: "Planner",
    cube: "Horadric Cube", "terror-zones": "Terror Zones", breakpoints: "Breakpoints", classes: "Classes", drops: "Drops", grail: "Holy Grail", patches: "Patches",
  } satisfies Record<D2rTabKey, string>,
  soon: "Soon",
  beta: "Beta",
  logoAlt: "Diablo II",
  resurrectedAlt: "Resurrected",
  tagline: "Runes, runewords, uniques, sets and a gear planner, with the game's official names in English and Spanish.",
  season: (n: number) => `Season ${n}`,
  ladder: "Ladder",
  patch: (v: string) => `Patch ${v}`,
  menu: { runewords: "Runewords", planner: "Gear planner", uniques: "Uniques" },
  stash: {
    title: "The Stash",
    lede: "Everything that can drop in Sanctuary.",
    runes: "Runes",
    runesN: (n: string) => `${n} runes`,
    runewords: "Runewords",
    runewordsN: (n: string) => `${n} runewords`,
    uniques: "Uniques",
    uniquesN: (n: string) => `${n} uniques`,
    sets: "Sets",
    setsN: (sets: string, items: string) => `${sets} sets · ${items} items`,
    bases: "Bases",
    basesN: (n: string) => `${n} weapons and armor`,
    gems: "Gems",
    gemsN: (n: string) => `${n} gems`,
    charms: "Charms",
    charmsN: "Small, Large and Grand",
    cube: "Horadric Cube",
    cubeN: (n: string) => `${n} recipes`,
  },
  tools: {
    title: "Tools",
    lede: "Free, in English and Spanish, no account needed.",
    runewords: { name: "What runeword can I make?", desc: "Tick the runes you have and see what you can make, and in which bases." },
    planner: { name: "Gear planner", desc: "Equip your character and see the total resistances, FCR, FHR, run speed, magic find and skills." },
    breakpoints: { name: "Breakpoints", desc: "How much FCR, FHR and FBR you need for each step, for every class and weapon, Warlock included." },
    terror: { name: "Terror Zones", desc: "All 34 zones by act, their monster level and the immunities of their monsters in Hell." },
    grail: { name: "Holy Grail", desc: "Tick every unique, set item, runeword and rune you find and see what you are missing, recipes included." },
    drops: { name: "Drop calculator", desc: "Where to farm any item, what every boss drops and a chest to open, Terror Zones included." },
  },
  runes: {
    title: (n: string) => `All ${n} runes`,
    lede: "Hover or tap a rune to see its level and the runewords it appears in.",
    level: (n: number) => `Required Level: ${n}`,
    appears: (n: number) => `Used in ${n} runeword${n === 1 ? "" : "s"}`,
    none: "Not used in any runeword",
    more: (n: number) => `and ${n} more`,
  },
  classes: {
    title: "Classes",
    lede: "All eight, including the Warlock from Reign of the Warlock.",
    isNew: "New",
    tabLede: "The eight classes and their three skill trees.",
    requires: "Requires",
    skills: "Every skill",
    reqLevel: (n: number) => `Required level: ${n}`,
  },
  events: {
    title: "World events",
    desc: {
      terror: "Terrorized zones raise their monsters' level and what they drop.",
      uber: "When Terror is unleashed upon Sanctuary, Uber Diablo appears.",
      pandemonium: "The keys, the three bosses' organs and Uber Tristram.",
      cow: "The game swears it doesn't exist.",
    } as Record<string, string>,
  },
  wiki: {
    search: "Search…",
    all: "All",
    noResults: "Nothing matches.",
    notFound: "That isn't in the game.",
    reqLevel: "Required level",
    level: "Level",
    newRotw: "Reign of the Warlock",
    ladderOnly: "Ladder only",
    sockets: (n: number) => `${n} sockets`,
    count: (n: string) => (n === "1" ? "1 result" : `${n} results`),
    slotsLong: ["In weapons", "In helms and body armor", "In shields"],
    slotsShort: ["Weapon", "Armor", "Shield"],
  },
  runesTab: {
    lede: "What each rune gives in weapons, armor and shields, from El to Zod.",
    usedIn: "Runewords with this rune",
    none: "No runeword uses it.",
  },
  rwTab: {
    lede: (n: string) => `All ${n} runewords, with their runes in order, the bases they go into and what they give.`,
    calc: "What can I make?",
    calcHint: "Tick the runes you have:",
    clear: "Clear",
    canMake: "You can make it",
    missing: (n: number) => `Missing ${n} rune${n === 1 ? "" : "s"}`,
    onlyMakeable: "Only what I can make",
    sockets: "Sockets",
    kind: { all: "All", 0: "Weapons", 1: "Armor and helms", 2: "Shields" } as Record<string, string>,
    onlyNew: "Only Reign of the Warlock",
    order: "Runes, in order",
    fitsIn: "Goes into",
    bases: (n: string) => `${n} bases`,
    variant: ["In a weapon", "In a helm or body armor", "In a shield"],
  },
  uniquesTab: {
    lede: (n: string) => `All ${n} unique items that can drop, by category.`,
    base: "Base",
  },
  setsTab: {
    lede: (n: string, m: string) => `All ${n} sets and their ${m} items, with every bonus.`,
    partial: (n: number) => `${n} items`,
    full: "Full set",
    items: "Items",
    setBonus: "Set bonuses",
    itemBonus: (n: number) => `(${n} items)`,
  },
  basesTab: {
    lede: "Every weapon and armor base, with its three tiers, requirements and maximum sockets.",
    tier: { n: "Normal", x: "Exceptional", e: "Elite" } as Record<string, string>,
    col: { name: "Name", def: "Defense", dmg: "Damage", speed: "Speed", str: "Str", dex: "Dex", lvl: "Level", sockets: "Sockets", block: "Block" },
    oneHand: "1H",
    twoHand: "2H",
  },
  patches: {
    lede: "Every patch of the Reign of the Warlock era, summarized: what changed and what it means for your character.",
    empty: "The patches are on their way.",
    version: (v: string) => `Patch ${v}`,
    official: "Official patch notes",
    officialPost: "Official launch announcement",
  },
  cube: {
    lede: (n: string) => `All ${n} Horadric Cube recipes, grouped.`,
    groups: {
      runes: "Runes", gems: "Gems", crafted: "Crafted items", sockets: "Sockets", upgrade: "Upgrades", reroll: "Rerolls",
      repair: "Repair and recharge", portals: "Portals and quests", potions: "Potions", misc: "Other recipes",
    } as Record<string, string>,
    families: { blood: "Blood", caster: "Caster", hitpower: "Hit Power", safety: "Safety" } as Record<string, string>,
    quals: {
      mag: "magic", rar: "rare", set: "set", uni: "unique", nor: "normal", low: "low quality", noe: "non-ethereal", nos: "no sockets",
      sock: "socketed", bas: "normal tier", exc: "exceptional", eli: "elite", upg: "or its exceptional/elite versions",
      crf: "crafted", mod: "keeps its stats", rep: "repaired", rch: "recharged", uns: "socketed items removed", pre: "fixed prefix", suf: "fixed suffix",
    } as Record<string, string>,
    sockets: (n: number) => `${n} sockets`,
    useitem: "The same item",
    usetype: "A new item of the same type",
    special: { "Cow Portal": "Cow Level portal", "Pandemonium Portal": "Pandemonium portal", "Pandemonium Finale Portal": "Uber Tristram portal", "Red Portal": "Colossal Ancients portal" } as Record<string, string>,
    hell: "Hell only",
  },
  bp: {
    lede: "How many animation frames each action takes: fewer is faster. Enter yours to see where you are and how far the next step is.",
    yours: "Your values",
    kinds: { fcr: "Faster cast rate (FCR)", fhr: "Faster hit recovery (FHR)", fbr: "Faster block rate (FBR)" } as Record<string, string>,
    frames: "Frames",
    needed: "You need",
    anyWeapon: "Any weapon",
    now: (f: number) => `${f} frames`,
    next: (pct: number, missing: number) => `Next: ${pct}% (${missing}% to go)`,
    maxed: "Top breakpoint",
    wclass: {
      HTH: "No weapon", "1HS": "One-hand swinging weapon", "1HT": "One-hand thrusting weapon", "2HS": "Two-hand swinging weapon",
      "2HT": "Spear", STF: "Staff or polearm", BOW: "Bow", XBW: "Crossbow", HT1: "One claw", HT2: "Two claws",
      "1JS": "Two weapons", "1JT": "Two weapons", "1SS": "Two weapons", "1ST": "Two weapons",
    } as Record<string, string>,
  },
  zones: {
    lede: (n: string, min: number) => `The ${n} areas that can become terrorized: every ${min} minutes one of them raises its monsters' level and what they drop. With the immunities of its monsters in Hell.`,
    levelTitle: "Monster level",
    diffs: { normal: "Normal", nightmare: "Nightmare", hell: "Hell" } as Record<string, string>,
    range: (a: number, b: number) => `Level ${a} to ${b}`,
    boost: (lvl: number, xp: number) => `Monsters sit ${lvl} levels above yours, inside that range, and give ${xp}% more experience.`,
    heralds: "Heralds (Hell)",
    heraldCols: { tier: "Tier", health: "Health", damage: "Damage", minions: "Minions", tc: "Loot level" },
    act: (n: number) => `Act ${n}`,
    waypoint: "Waypoint",
    immune: "Immunities in Hell",
    none: "No immunities",
    monsters: (n: number) => `${n} monsters`,
    elements: { physical: "Physical", magic: "Magic", fire: "Fire", light: "Lightning", cold: "Cold", poison: "Poison" } as Record<string, string>,
  },
  planner: {
    title: "Gear planner",
    lede: "Equip your character and see the totals. Pick a slot to choose an item.",
    cls: "Class",
    level: "Level",
    difficulty: "Difficulty",
    diffs: ["Normal", "Nightmare", "Hell"],
    values: "Values",
    max: "Perfect",
    min: "Minimum",
    slots: {
      head: "Helm", amulet: "Amulet", weapon: "Weapon", body: "Body armor", shield: "Shield", gloves: "Gloves",
      belt: "Belt", boots: "Boots", ring1: "Ring", ring2: "Ring", charm: "Charms",
    } as Record<string, string>,
    choose: "Choose an item",
    remove: "Remove",
    close: "Close",
    searchItem: "Search an item…",
    totals: "Totals",
    resist: "Resistances",
    res: { fire: "Fire", cold: "Cold", light: "Lightning", poison: "Poison" } as Record<string, string>,
    resGear: (n: number) => `${n < 0 ? "−" : "+"}${Math.abs(n)} from gear`,
    resOver: (n: number) => `+${n} over the cap`,
    resPenalty: (diff: string, n: number) => `${diff}: every resistance starts at −${n}%, as on the game's character sheet.`,
    speeds: "Speeds",
    fcr: "Faster cast rate",
    fhr: "Faster hit recovery",
    fbr: "Faster block rate",
    ias: "Increased attack speed",
    frw: "Faster run/walk",
    finds: "Magic and gold",
    mf: "Magic find",
    gf: "Extra gold",
    allStats: "Every stat",
    empty: "Equip something to see the totals.",
    share: "Copy link",
    copied: "Link copied",
    clear: "Empty all",
    reqWarn: (lvl: number) => `Needs level ${lvl}`,
    setsActive: "Active sets",
    kindRw: "Runeword",
    kindUnique: "Unique",
    kindSet: "Set",
    addCharm: "Add a charm",
  },
  grail: {
    lede: (u: string, s: string, w: string, r: string) =>
      `Tick what you have found. The same lists as the in-game Chronicle (${u} uniques, ${s} set items and ${w} runewords) plus the ${r} runes, and what you are missing shows in full, runes in order included. Your progress stays in this browser.`,
    lists: { u: "Uniques", s: "Set items", w: "Runewords", r: "Runes" },
    total: "Chronicle",
    reward: "Chronicle reward",
    complete: "Complete",
    share: "Copy link",
    copied: "Link copied",
    reset: "Start over",
    resetSure: "Tap again to erase it all",
    shared: (n: string, total: string) => `You are looking at someone else's Grail: ${n} of ${total}.`,
    keep: "Make it mine",
    mine: "Back to mine",
  },
  drops: {
    title: "Drop calculator",
    lede: "Where to farm any item, what every boss drops and a chest to open. Terror Zones included.",
    about: [
      "Search an item and you get the best bosses to farm it (chance per kill: one kill is one run) and the best areas (chance per monster). Change your magic find, the players in the game or turn on a Terror Zone with your level and everything updates.",
      "The numbers are exact: they count the six-items-per-kill cap, Terror Zones and Heralds.",
    ],
    modes: { farm: "Where do I farm it?", drops: "What does it drop?", sim: "Simulator" },
    search: "Search an item: Shako, Ber, Tal Rasha…",
    examples: "Try",
    noHits: "Nothing by that name.",
    kinds: { u: "Unique", s: "Set", r: "Rune", b: "Base" },
    mf: "Magic find",
    players: "Players",
    party: "Party members nearby",
    diff: "Difficulty",
    allDiffs: "All",
    diffs: ["Normal", "Nightmare", "Hell"],
    tz: "Terror Zone",
    tzLevel: "Your level",
    more: "More options",
    ladder: "Ladder",
    quest: "First quest kill",
    herald: "Herald tier",
    bosses: "Bosses and super uniques",
    bossesNote: "Chance per kill: one kill is one run.",
    areas: "Areas",
    areasNote: "Chance per monster killed, by type.",
    // "Regular" y no "Normal": "Normal" ya es una dificultad y en una fila decía "Best area · Normal · Normal".
    cats: { normal: "Regular", champ: "Champion", unique: "Unique", herald: "Herald" },
    kindBoss: "Boss",
    kindSuper: "Super unique",
    tzBadge: "Terror Zone",
    act: (n: number) => `Act ${n}`,
    level: (n: number) => `level ${n}`,
    oneIn: (n: string) => `1 in ${n}`,
    million: (n: string) => `${n} million`,
    pct: (n: string) => `${n}%`,
    none: "Nothing drops it with these options.",
    noneLadder: "This season it only drops on Ladder.",
    ladderOn: "Turn on Ladder",
    noneEver: "No monster drops it.",
    pick: "Search an item to see where to farm it.",
    whatElse: "What else does it drop?",
    why: "Where does this number come from?",
    pathRoot: (tc: string, picks: number) => (picks >= 0 ? `${tc}: ${picks} ${picks === 1 ? "pick" : "picks"}` : `${tc}: ${-picks} ${picks === -1 ? "fixed item" : "fixed items"}`),
    pathStep: (tc: string, odds: string) => `→ ${tc} (${odds} per pick)`,
    pathSure: (tc: string) => `→ ${tc} (always)`,
    pathMore: (n: number) => `${n} more steps`,
    always: "always",
    pathItem: (name: string, odds: string) => `→ ${name} (${odds})`,
    pathQuality: (odds: string, set: boolean) => `→ ${set ? "set" : "unique"} quality: ${odds} with your magic find`,
    pathPick: (odds: string) => `→ among the possible ones for that base: ${odds}`,
    tcWeap: (n: string) => `weapons up to level ${n}`,
    tcArmo: (n: string) => `armor up to level ${n}`,
    tcMele: (n: string) => `melee weapons up to level ${n}`,
    tcBow: (n: string) => `bows up to level ${n}`,
    tcRunes: (n: string) => `runes (group ${n})`,
    // Los tipos de los TC de acto ("Act 5 (N) Equip C" → "Act 5 · Nightmare · equipment").
    tcKinds: {
      Equip: "equipment",
      Good: "good loot",
      Uitem: "unique loot",
      Citem: "champion loot",
      Melee: "melee weapons",
      Bow: "bows",
      Magic: "magic items",
      Junk: "junk",
      H2H: "melee monsters",
      Miss: "ranged monsters",
      Cast: "casters",
      Champ: "champions",
      Unique: "uniques",
      Super: "super uniques",
      Chest: "chests",
      Wraith: "wraiths",
      Cpot: "potions",
      Herald: "Herald",
    },
    mfTitle: "How much magic find helps",
    mfSentence: (a: string, b: string) => `From 0 to 300% magic find the chance goes ×${a}; from 300 to 600%, only ×${b}.`,
    mfChart: (a: string, b: string) => `Chance by magic find: ${a} at 0%, ${b} at 1,000%.`,
    mfNoEffect: "Magic find doesn't change this chance.",
    place: "Place",
    monsterType: "Monster type",
    pickPlace: "Choose a boss, a super unique or an area",
    pickSource: "Choose a boss or super unique",
    bossGroup: "Bosses and super uniques",
    areaGroup: (n: number) => `Areas of Act ${n}`,
    runes: "Runes",
    uniques: "Uniques",
    sets: "Set items",
    showAll: (n: number) => `Show all (${n})`,
    noDrops: "Nothing drops here with these options.",
    calculating: "calculating…",
    runs: "Runs",
    open: "Open the chest",
    again: "Open another",
    simLede: (runs: string, name: string) => `${runs} ${runs === "1" ? "run" : "runs"} of ${name}:`,
    simEmpty: "Choose a boss or super unique and open the chest.",
    simNothing: "Nothing special this time. Open another one.",
    rares: (n: string) => (n === "1" ? "1 rare" : `${n} rares`),
    magics: (n: string) => `${n} magic`,
    normals: (n: string) => `${n} normal`,
    gold: (n: string) => (n === "1" ? "1 gold pile" : `${n} gold piles`),
    share: "Copy link",
    copied: "Link copied",
    sourceTitle: (name: string) => `${name} drops`,
    sourceLede: (name: string) => `Every rune, unique and set item ${name} can drop, with its chance per kill. Change the difficulty, your magic find or the players.`,
    openCalc: "Open in the calculator",
    openSim: "Open in the simulator",
    sourcesTitle: "What every boss drops",
    sourcesEvents: "Events",
    farmTitle: "Where to farm it",
    farmPieces: "Where to farm each piece",
    // La unidad de cada cifra: por muerte en los jefes y por monstruo en el área (que sólo se nombra si el bloque la trae).
    farmNote: (area: boolean) => `Per kill, with 1 player and 300% magic find${area ? "; in the area, per monster" : ""}.`,
    farmNoteLadder: (area: boolean) => `Per kill, with 1 player and 300% magic find, on Ladder (this season it only drops there)${area ? "; in the area, per monster" : ""}.`,
    bestArea: "Best area",
    back: "Drop calculator",
  },
};

const ES: typeof EN = {
  seo: {
    title: "Runas y palabras rúnicas de Diablo 2 Resurrected en español | Vestigo",
    description:
      "Las 33 runas de Diablo II: Resurrected con su nivel y sus palabras rúnicas, y todo lo que puede caer en Santuario —únicos, conjuntos, bases y el Cubo horádrico— con los nombres oficiales del juego.",
    runes: { title: "Runas de Diablo 2 Resurrected: las 33 runas y qué dan | Vestigo", description: "Todas las runas de Diablo II: Resurrected, de El a Zod: qué dan en armas, armaduras y escudos, su nivel requerido y las palabras rúnicas que forman." },
    rune: (name: string) => ({ title: `${name} de Diablo 2 Resurrected: efectos y palabras rúnicas | Vestigo`, description: `${name} en Diablo II: Resurrected: qué da en armas, armaduras y escudos, su nivel requerido y todas las palabras rúnicas que la usan.` }),
    runewords: { title: "Palabras rúnicas de Diablo 2 Resurrected: lista y calculadora | Vestigo", description: "Todas las palabras rúnicas de Diablo II: Resurrected con sus runas en orden, las bases donde entran y sus stats. Marcá las runas que tenés y mirá qué podés armar." },
    runeword: (name: string) => ({ title: `${name}: palabra rúnica de Diablo 2 Resurrected | Vestigo`, description: `Palabra rúnica ${name} en Diablo II: Resurrected: runas en orden, bases donde entra, nivel requerido y todas sus stats.` }),
    uniques: { title: "Únicos de Diablo 2 Resurrected: todos los objetos únicos | Vestigo", description: "Todos los objetos únicos que pueden caer en Diablo II: Resurrected, por categoría, con su base, su nivel requerido y sus stats." },
    unique: (name: string) => ({ title: `${name}: único de Diablo 2 Resurrected | Vestigo`, description: `${name} en Diablo II: Resurrected: objeto base, nivel requerido y todas sus stats con su rango.` }),
    sets: { title: "Conjuntos de Diablo 2 Resurrected: todos los sets y sus bonificaciones | Vestigo", description: "Todos los conjuntos de Diablo II: Resurrected con sus piezas, las bonificaciones por cantidad de piezas y la del conjunto completo." },
    set: (name: string) => ({ title: `${name}: conjunto de Diablo 2 Resurrected | Vestigo`, description: `${name} en Diablo II: Resurrected: todas las piezas del conjunto, sus stats y las bonificaciones con 2, 3 y todas las piezas.` }),
    bases: { title: "Bases de Diablo 2 Resurrected: armas y armaduras | Vestigo", description: "Todas las bases de armas y armaduras de Diablo II: Resurrected: normales, excepcionales y de élite, con defensa, daño, requisitos y engarces máximos." },
    classes: { title: "Clases de Diablo 2 Resurrected y sus árboles de habilidades | Vestigo", description: "Las ocho clases de Diablo II: Resurrected, con el Conjurador, y sus tres árboles de habilidades: cada habilidad, su nivel requerido, lo que pide antes y lo que hace." },
    patches: { title: "Parches de Diablo 2 Resurrected explicados en español | Vestigo", description: "Cada parche de Diablo II: Resurrected desde Reign of the Warlock, resumido en español: qué cambió, qué significa para tu personaje y el enlace a las notas oficiales." },
    patch: (name: string) => ({ title: `Parche ${name} de Diablo 2 Resurrected: qué cambió | Vestigo`, description: `El parche ${name} de Diablo II: Resurrected resumido en español: cada cambio importante y qué significa para tu personaje.` }),
    cube: { title: "Cubo horádrico de Diablo 2 Resurrected: todas las recetas | Vestigo", description: "Todas las recetas del Cubo horádrico de Diablo II: Resurrected: runas y gemas, objetos creados con sus stats, engarces, mejoras, portales y más." },
    breakpoints: { title: "Breakpoints de Diablo 2 Resurrected: FCR, FHR y FBR de cada clase (con el Conjurador) | Vestigo", description: "Los breakpoints de velocidad de lanzamiento, recuperación de golpe y velocidad de bloqueo de cada clase de Diablo II: Resurrected y cada tipo de arma, con el Conjurador. Poné los tuyos y mirá cuánto te falta para el siguiente." },
    "terror-zones": { title: "Zonas de Terror de Diablo 2 Resurrected: lista, niveles e inmunidades | Vestigo", description: "Las 34 Zonas de Terror de Diablo II: Resurrected por acto: sus áreas, el waypoint, el nivel de los monstruos en cada dificultad, los Heraldos de Infierno y las inmunidades de cada monstruo en Infierno." },
    cls: (name: string) => ({ title: `Habilidades de ${name} en Diablo 2 Resurrected: árbol completo | Vestigo`, description: `Todas las habilidades de ${name} en Diablo II: Resurrected, árbol por árbol: nivel requerido, requisitos y qué hace cada una.` }),
    grail: { title: "Grial de Diablo 2 Resurrected: marcá tus únicos, conjuntos y palabras rúnicas | Vestigo", description: "Seguí tu Grial de Diablo II: Resurrected: marcá cada único, pieza de conjunto, palabra rúnica y runa que encontrás, mirá qué te falta con su receta y compartí tu progreso con un enlace. Gratis y sin cuenta." },
    drops: { title: "Calculadora de drops de Diablo 2 Resurrected: dónde farmear cada ítem | Vestigo", description: "Dónde farmear cada único, pieza de conjunto, runa o base de Diablo II: Resurrected: los mejores jefes y áreas con su chance exacta, con tu hallazgo mágico y tus jugadores, Zonas de Terror y Heraldos incluidos. Además, qué suelta cada jefe y un simulador de botín." },
    dropsSource: (name: string) => ({ title: `Qué suelta ${name} en Diablo 2 Resurrected: runas, únicos y conjuntos | Vestigo`, description: `Cada runa, único y pieza de conjunto que puede soltar ${name} en Diablo II: Resurrected, con su chance exacta por muerte en Normal, Pesadilla e Infierno.` }),
    planner: { title: "Planificador de equipo de Diablo 2 Resurrected: sumá las stats | Vestigo", description: "Equipá únicos, conjuntos y palabras rúnicas en tu personaje de Diablo II: Resurrected y mirá las resistencias, FCR, FHR, velocidad, hallazgo mágico y habilidades totales. Gratis, se comparte con un enlace." },
  },
  tabs: {
    home: "Inicio", runes: "Runas", runewords: "Palabras rúnicas", uniques: "Únicos", sets: "Conjuntos", bases: "Bases", planner: "Planificador",
    cube: "Cubo horádrico", "terror-zones": "Zonas de Terror", breakpoints: "Breakpoints", classes: "Clases", drops: "Drops", grail: "Grial", patches: "Parches",
  },
  soon: "Pronto",
  beta: "Beta",
  logoAlt: "Diablo II",
  resurrectedAlt: "Resurrected",
  tagline: "Runas, palabras rúnicas, únicos, conjuntos y un planificador de equipo, con los nombres oficiales del juego en español.",
  season: (n: number) => `Temporada ${n}`,
  ladder: "Clasificación",
  patch: (v: string) => `Parche ${v}`,
  menu: { runewords: "Palabras rúnicas", planner: "Planificador de equipo", uniques: "Únicos" },
  stash: {
    title: "El Arcón",
    lede: "Todo lo que puede caer en Santuario.",
    runes: "Runas",
    runesN: (n: string) => `${n} runas`,
    runewords: "Palabras rúnicas",
    runewordsN: (n: string) => `${n} palabras`,
    uniques: "Únicos",
    uniquesN: (n: string) => `${n} únicos`,
    sets: "Conjuntos",
    setsN: (sets: string, items: string) => `${sets} conjuntos · ${items} piezas`,
    bases: "Bases",
    basesN: (n: string) => `${n} armas y armaduras`,
    gems: "Gemas",
    gemsN: (n: string) => `${n} gemas`,
    charms: "Talismanes",
    charmsN: "Pequeño, grande y gran talismán",
    cube: "Cubo horádrico",
    cubeN: (n: string) => `${n} recetas`,
  },
  tools: {
    title: "Herramientas",
    lede: "Gratis, en español y sin cuenta.",
    runewords: { name: "¿Qué palabra rúnica armo?", desc: "Marcá las runas que tenés y te mostramos qué podés armar y en qué bases." },
    planner: { name: "Planificador de equipo", desc: "Equipá a tu personaje y mirá las resistencias, FCR, FHR, velocidad, hallazgo mágico y habilidades totales." },
    breakpoints: { name: "Breakpoints", desc: "Cuánta FCR, FHR y FBR necesitás para cada escalón, de cada clase y arma, con el Conjurador." },
    terror: { name: "Zonas de Terror", desc: "Las 34 zonas por acto, el nivel de sus monstruos y sus inmunidades en Infierno." },
    grail: { name: "Grial", desc: "Marcá cada único, pieza de conjunto, palabra rúnica y runa que encontrás y mirá qué te falta, con sus runas." },
    drops: { name: "Calculadora de drops", desc: "Dónde farmear cada ítem, qué suelta cada jefe y un cofre para abrir, con las Zonas de Terror." },
  },
  runes: {
    title: (n: string) => `Las ${n} runas`,
    lede: "Pasá el mouse o tocá una runa para ver su nivel y en qué palabras rúnicas aparece.",
    level: (n: number) => `Nivel requerido: ${n}`,
    appears: (n: number) => `Aparece en ${n} palabra${n === 1 ? "" : "s"} rúnica${n === 1 ? "" : "s"}`,
    none: "No aparece en ninguna palabra rúnica",
    more: (n: number) => `y ${n} más`,
  },
  classes: {
    title: "Clases",
    lede: "Las ocho, con el Conjurador de Reign of the Warlock.",
    isNew: "Nueva",
    tabLede: "Las ocho clases y sus tres árboles de habilidades.",
    requires: "Requiere",
    skills: "Todas las habilidades",
    reqLevel: (n: number) => `Nivel requerido: ${n}`,
  },
  events: {
    title: "Eventos del mundo",
    desc: {
      terror: "Las zonas aterrorizadas suben el nivel de sus monstruos y lo que sueltan.",
      uber: "Cuando el Terror se libera sobre Santuario, aparece Uber Diablo.",
      pandemonium: "Las llaves, los órganos de los tres jefes y el Tristram de los Uber.",
      cow: "El juego jura que no existe.",
    },
  },
  wiki: {
    search: "Buscar…",
    all: "Todos",
    noResults: "No hay coincidencias.",
    notFound: "Eso no está en el juego.",
    reqLevel: "Nivel requerido",
    level: "Nivel",
    newRotw: "Reign of the Warlock",
    ladderOnly: "Sólo en Clasificación",
    sockets: (n: number) => `${n} engarces`,
    count: (n: string) => (n === "1" ? "1 resultado" : `${n} resultados`),
    slotsLong: ["En armas", "En yelmos y armaduras", "En escudos"],
    slotsShort: ["Arma", "Armadura", "Escudo"],
  },
  runesTab: {
    lede: "Qué da cada runa en armas, armaduras y escudos, de El a Zod.",
    usedIn: "Palabras rúnicas con esta runa",
    none: "Ninguna palabra rúnica la usa.",
  },
  rwTab: {
    lede: (n: string) => `Las ${n} palabras rúnicas, con sus runas en orden, las bases donde entran y lo que dan.`,
    calc: "¿Qué puedo armar?",
    calcHint: "Marcá las runas que tenés:",
    clear: "Borrar",
    canMake: "La podés armar",
    missing: (n: number) => `Te falta${n === 1 ? "" : "n"} ${n} runa${n === 1 ? "" : "s"}`,
    onlyMakeable: "Sólo lo que puedo armar",
    sockets: "Engarces",
    kind: { all: "Todas", 0: "Armas", 1: "Armaduras y yelmos", 2: "Escudos" },
    onlyNew: "Sólo Reign of the Warlock",
    order: "Runas, en orden",
    fitsIn: "Entra en",
    bases: (n: string) => `${n} bases`,
    variant: ["En un arma", "En un yelmo o armadura", "En un escudo"],
  },
  uniquesTab: {
    lede: (n: string) => `Los ${n} objetos únicos que pueden caer, por categoría.`,
    base: "Base",
  },
  setsTab: {
    lede: (n: string, m: string) => `Los ${n} conjuntos y sus ${m} piezas, con todas las bonificaciones.`,
    partial: (n: number) => `${n} piezas`,
    full: "Conjunto completo",
    items: "Piezas",
    setBonus: "Bonificaciones del conjunto",
    itemBonus: (n: number) => `(${n} piezas)`,
  },
  basesTab: {
    lede: "Todas las bases de armas y armaduras, con sus tres niveles, requisitos y engarces máximos.",
    tier: { n: "Normal", x: "Excepcional", e: "Élite" },
    col: { name: "Nombre", def: "Defensa", dmg: "Daño", speed: "Velocidad", str: "Fue", dex: "Des", lvl: "Nivel", sockets: "Engarces", block: "Bloqueo" },
    oneHand: "1M",
    twoHand: "2M",
  },
  patches: {
    lede: "Cada parche desde Reign of the Warlock, resumido: qué cambió y qué significa para tu personaje.",
    empty: "Los parches están en camino.",
    version: (v: string) => `Parche ${v}`,
    official: "Notas oficiales del parche",
    officialPost: "Anuncio oficial del lanzamiento",
  },
  cube: {
    lede: (n: string) => `Las ${n} recetas del Cubo horádrico, por grupo.`,
    groups: {
      runes: "Runas", gems: "Gemas", crafted: "Objetos creados", sockets: "Engarces", upgrade: "Mejoras", reroll: "Transmutaciones",
      repair: "Reparar y recargar", portals: "Portales y misiones", potions: "Pociones", misc: "Otras recetas",
    },
    families: { blood: "Sangre", caster: "Lanzador", hitpower: "Golpe poderoso", safety: "Seguridad" },
    quals: {
      mag: "calidad mágica", rar: "calidad rara", set: "de conjunto", uni: "calidad única", nor: "calidad normal", low: "baja calidad", noe: "no etéreo", nos: "sin engarces",
      sock: "con engarces", bas: "nivel normal", exc: "nivel excepcional", eli: "nivel de élite", upg: "o sus versiones excepcional y de élite",
      crf: "creado", mod: "conserva sus propiedades", rep: "reparado", rch: "recargado", uns: "sin lo engarzado", pre: "prefijo fijo", suf: "sufijo fijo",
    },
    sockets: (n: number) => `${n} engarces`,
    useitem: "El mismo objeto",
    usetype: "Un objeto nuevo del mismo tipo",
    special: { "Cow Portal": "Portal al Nivel de la Vaca", "Pandemonium Portal": "Portal al Pandemonio", "Pandemonium Finale Portal": "Portal a Tristram de los Uber", "Red Portal": "Portal a los Ancestros Colosales" },
    hell: "Sólo en Infierno",
  },
  bp: {
    lede: "Cuántos cuadros de animación tarda cada acción: menos es más rápido. Poné los tuyos para ver en qué escalón estás y cuánto te falta para el siguiente.",
    yours: "Tus valores",
    kinds: { fcr: "Velocidad de lanzamiento (FCR)", fhr: "Recuperación de golpe (FHR)", fbr: "Velocidad de bloqueo (FBR)" },
    frames: "Cuadros",
    needed: "Necesitás",
    anyWeapon: "Con cualquier arma",
    now: (f: number) => `${f} cuadros`,
    next: (pct: number, missing: number) => `Siguiente: ${pct}% (te falta ${missing}%)`,
    maxed: "Último escalón",
    wclass: {
      HTH: "Sin arma", "1HS": "Arma de una mano (golpe)", "1HT": "Arma de una mano (estocada)", "2HS": "Arma de dos manos (golpe)",
      "2HT": "Lanza", STF: "Báculo o arma de asta", BOW: "Arco", XBW: "Ballesta", HT1: "Una garra", HT2: "Dos garras",
      "1JS": "Dos armas", "1JT": "Dos armas", "1SS": "Dos armas", "1ST": "Dos armas",
    },
  },
  zones: {
    lede: (n: string, min: number) => `Las ${n} áreas que pueden quedar aterrorizadas: cada ${min} minutos una sube el nivel de sus monstruos y lo que sueltan. Con las inmunidades de sus monstruos en Infierno.`,
    levelTitle: "Nivel de los monstruos",
    diffs: { normal: "Normal", nightmare: "Pesadilla", hell: "Infierno" },
    range: (a: number, b: number) => `Nivel ${a} a ${b}`,
    boost: (lvl: number, xp: number) => `Los monstruos quedan ${lvl} niveles arriba del tuyo, dentro de ese rango, y dan ${xp}% más de experiencia.`,
    heralds: "Heraldos (Infierno)",
    heraldCols: { tier: "Nivel", health: "Vida", damage: "Daño", minions: "Esbirros", tc: "Nivel del botín" },
    act: (n: number) => `Acto ${n}`,
    waypoint: "Waypoint",
    immune: "Inmunidades en Infierno",
    none: "Sin inmunidades",
    monsters: (n: number) => `${n} monstruos`,
    elements: { physical: "Físico", magic: "Mágico", fire: "Fuego", light: "Rayo", cold: "Frío", poison: "Veneno" },
  },
  planner: {
    title: "Planificador de equipo",
    lede: "Equipá a tu personaje y mirá los totales. Tocá un casillero para elegir un ítem.",
    cls: "Clase",
    level: "Nivel",
    difficulty: "Dificultad",
    diffs: ["Normal", "Pesadilla", "Infierno"],
    values: "Valores",
    max: "Perfectos",
    min: "Mínimos",
    slots: {
      head: "Yelmo", amulet: "Amuleto", weapon: "Arma", body: "Armadura", shield: "Escudo", gloves: "Guantes",
      belt: "Cinturón", boots: "Botas", ring1: "Anillo", ring2: "Anillo", charm: "Talismanes",
    },
    choose: "Elegí un ítem",
    remove: "Sacar",
    close: "Cerrar",
    searchItem: "Buscar un ítem…",
    totals: "Totales",
    resist: "Resistencias",
    res: { fire: "Fuego", cold: "Frío", light: "Rayo", poison: "Veneno" },
    resGear: (n: number) => `${n < 0 ? "−" : "+"}${Math.abs(n)} del equipo`,
    resOver: (n: number) => `+${n} sobre el tope`,
    resPenalty: (diff: string, n: number) => `${diff}: cada resistencia arranca en −${n}%, como en la hoja del personaje del juego.`,
    speeds: "Velocidades",
    fcr: "Velocidad de lanzamiento",
    fhr: "Recuperación de golpe",
    fbr: "Velocidad de bloqueo",
    ias: "Velocidad de ataque",
    frw: "Velocidad al correr/caminar",
    finds: "Hallazgo",
    mf: "Hallazgo mágico",
    gf: "Oro adicional",
    allStats: "Todas las stats",
    empty: "Equipá algo para ver los totales.",
    share: "Copiar enlace",
    copied: "Enlace copiado",
    clear: "Vaciar todo",
    reqWarn: (lvl: number) => `Necesita nivel ${lvl}`,
    setsActive: "Conjuntos activos",
    kindRw: "Palabra rúnica",
    kindUnique: "Único",
    kindSet: "Conjunto",
    addCharm: "Agregar un talismán",
  },
  grail: {
    lede: (u: string, s: string, w: string, r: string) =>
      `Marcá lo que ya encontraste. Son las mismas listas que la Crónica del juego (${u} únicos, ${s} piezas de conjunto y ${w} palabras rúnicas) más las ${r} runas, y lo que te falta se ve entero, con sus runas en orden. Tu progreso queda guardado en este navegador.`,
    lists: { u: "Únicos", s: "Piezas de conjunto", w: "Palabras rúnicas", r: "Runas" },
    total: "Crónica",
    reward: "Recompensa de la Crónica",
    complete: "Completo",
    share: "Copiar enlace",
    copied: "Enlace copiado",
    reset: "Empezar de nuevo",
    resetSure: "Tocá de nuevo para borrar todo",
    shared: (n: string, total: string) => `Estás mirando el Grial de otra persona: ${n} de ${total}.`,
    keep: "Quedármelo",
    mine: "Volver al mío",
  },
  drops: {
    title: "Calculadora de drops",
    lede: "Dónde farmear cada ítem, qué suelta cada jefe y un cofre para abrir. Con las Zonas de Terror.",
    about: [
      "Buscá un ítem y te muestra los mejores jefes para farmearlo (chance por muerte: cada muerte es una run) y las mejores áreas (chance por monstruo). Cambiá tu hallazgo mágico, los jugadores de la partida o prendé una Zona de Terror con tu nivel y todo se actualiza.",
      "Los números son exactos: cuentan el tope de seis ítems por muerte, las Zonas de Terror y los Heraldos.",
    ],
    modes: { farm: "¿Dónde lo farmeo?", drops: "¿Qué suelta?", sim: "Simulador" },
    search: "Buscá un ítem: Shako, Ber, Tal Rasha…",
    examples: "Probá con",
    noHits: "No hay nada con ese nombre.",
    kinds: { u: "Único", s: "Conjunto", r: "Runa", b: "Base" },
    mf: "Hallazgo mágico",
    players: "Jugadores",
    party: "Del grupo cerca tuyo",
    diff: "Dificultad",
    allDiffs: "Todas",
    diffs: ["Normal", "Pesadilla", "Infierno"],
    tz: "Zona de Terror",
    tzLevel: "Tu nivel",
    more: "Más opciones",
    ladder: "Clasificación",
    quest: "Primera muerte de la misión",
    herald: "Nivel del Heraldo",
    bosses: "Jefes y superúnicos",
    bossesNote: "Chance por muerte: cada muerte es una run.",
    areas: "Áreas",
    areasNote: "Chance por cada monstruo que matás, según su tipo.",
    cats: { normal: "Común", champ: "Campeón", unique: "Único", herald: "Heraldo" },
    kindBoss: "Jefe",
    kindSuper: "Superúnico",
    tzBadge: "Zona de Terror",
    act: (n: number) => `Acto ${n}`,
    level: (n: number) => `nivel ${n}`,
    oneIn: (n: string) => `1 en ${n}`,
    million: (n: string) => (n === "1" ? "1 millón" : `${n} millones`),
    // Pegado al número, como el resto del español del sitio ("300%"); así tampoco queda solo en el renglón de abajo.
    pct: (n: string) => `${n}%`,
    none: "Con estas opciones no lo suelta nadie.",
    noneLadder: "Esta temporada sólo cae en Clasificación.",
    ladderOn: "Prender Clasificación",
    noneEver: "No lo suelta ningún monstruo.",
    pick: "Buscá un ítem para ver dónde farmearlo.",
    whatElse: "¿Qué más suelta?",
    why: "¿De dónde sale este número?",
    pathRoot: (tc: string, picks: number) => (picks >= 0 ? `${tc}: ${picks} ${picks === 1 ? "tirada" : "tiradas"}` : `${tc}: ${-picks} ${picks === -1 ? "ítem fijo" : "ítems fijos"}`),
    pathStep: (tc: string, odds: string) => `→ ${tc} (${odds} por tirada)`,
    pathSure: (tc: string) => `→ ${tc} (siempre)`,
    pathMore: (n: number) => `${n} pasos más`,
    always: "siempre",
    pathItem: (name: string, odds: string) => `→ ${name} (${odds})`,
    pathQuality: (odds: string, set: boolean) => `→ calidad ${set ? "de conjunto" : "única"}: ${odds} con tu hallazgo mágico`,
    pathPick: (odds: string) => `→ entre los posibles de esa base: ${odds}`,
    tcWeap: (n: string) => `armas hasta nivel ${n}`,
    tcArmo: (n: string) => `armaduras hasta nivel ${n}`,
    tcMele: (n: string) => `armas cuerpo a cuerpo hasta nivel ${n}`,
    tcBow: (n: string) => `arcos hasta nivel ${n}`,
    tcRunes: (n: string) => `runas (grupo ${n})`,
    // Los tipos de los TC de acto ("Act 5 (N) Equip C" → "Acto 5 · Pesadilla · equipo").
    tcKinds: {
      Equip: "equipo",
      Good: "botín bueno",
      Uitem: "botín de únicos",
      Citem: "botín de campeones",
      Melee: "armas cuerpo a cuerpo",
      Bow: "arcos",
      Magic: "ítems mágicos",
      Junk: "baratijas",
      H2H: "monstruos cuerpo a cuerpo",
      Miss: "monstruos a distancia",
      Cast: "hechiceros",
      Champ: "campeones",
      Unique: "únicos",
      Super: "superúnicos",
      Chest: "cofres",
      Wraith: "espectros",
      Cpot: "pociones",
      Herald: "Heraldo",
    },
    mfTitle: "Cuánto te suma el hallazgo mágico",
    mfSentence: (a: string, b: string) => `De 0 a 300% de hallazgo mágico la chance se multiplica por ${a}; de 300 a 600%, sólo por ${b}.`,
    mfChart: (a: string, b: string) => `Chance según el hallazgo mágico: ${a} con 0%, ${b} con 1.000%.`,
    mfNoEffect: "El hallazgo mágico no cambia esta chance.",
    place: "Lugar",
    monsterType: "Tipo de monstruo",
    pickPlace: "Elegí un jefe, un superúnico o un área",
    pickSource: "Elegí un jefe o superúnico",
    bossGroup: "Jefes y superúnicos",
    areaGroup: (n: number) => `Áreas del Acto ${n}`,
    runes: "Runas",
    uniques: "Únicos",
    sets: "Piezas de conjunto",
    showAll: (n: number) => `Ver todo (${n})`,
    noDrops: "Con estas opciones acá no cae nada.",
    calculating: "calculando…",
    runs: "Runs",
    open: "Abrir el cofre",
    again: "Abrir otro",
    simLede: (runs: string, name: string) => `${runs} ${runs === "1" ? "run" : "runs"} de ${name}:`,
    simEmpty: "Elegí un jefe o superúnico y abrí el cofre.",
    simNothing: "Esta vez nada especial. Abrí otro.",
    rares: (n: string) => (n === "1" ? "1 raro" : `${n} raros`),
    magics: (n: string) => (n === "1" ? "1 mágico" : `${n} mágicos`),
    normals: (n: string) => (n === "1" ? "1 normal" : `${n} normales`),
    gold: (n: string) => (n === "1" ? "1 montón de oro" : `${n} montones de oro`),
    share: "Copiar enlace",
    copied: "Enlace copiado",
    sourceTitle: (name: string) => `Qué suelta ${name}`,
    sourceLede: (name: string) => `Cada runa, único y pieza de conjunto que puede soltar ${name}, con su chance por muerte. Cambiá la dificultad, tu hallazgo mágico o los jugadores.`,
    openCalc: "Abrir en la calculadora",
    openSim: "Abrir en el simulador",
    sourcesTitle: "Qué suelta cada jefe",
    sourcesEvents: "Eventos",
    farmTitle: "Dónde farmearlo",
    farmPieces: "Dónde farmear cada pieza",
    farmNote: (area: boolean) => `Por muerte, con 1 jugador y 300% de hallazgo mágico${area ? "; en el área, por monstruo" : ""}.`,
    farmNoteLadder: (area: boolean) => `Por muerte, con 1 jugador y 300% de hallazgo mágico, en Clasificación (esta temporada sólo cae ahí)${area ? "; en el área, por monstruo" : ""}.`,
    bestArea: "Mejor área",
    back: "Calculadora de drops",
  },
};

export type D2rCopy = typeof EN;
export const D2R_COPY: Record<"en" | "es", D2rCopy> = { en: EN, es: ES };
export const useD2rCopy = () => D2R_COPY[useLang().lang];
