/**
 * Textos de la Enciclopedia y del Diario de parches de PoE2.
 *
 * Aparte de `i18n.ts` por el mismo motivo que `newsCopy.ts`: son muchos y sólo
 * los usan estas dos pestañas. Los nombres de las propiedades de objeto siguen
 * los del juego en cada idioma ("Evasión", "Escudo de energía").
 */
import { useLang } from "./i18n";

const EN = {
  enc: {
    title: "Encyclopedia",
    lede: "Every gem, unique, base and currency item in the game, as the game shows it.",
    loading: "Opening the encyclopedia…",
    notFound: "That entry isn't in the encyclopedia.",
    search: "Search the whole encyclopedia…",
    searchCat: "Search this category…",
    noResults: "Nothing matches.",
    count: (n: number) => `${n} entries`,
    all: "All",
    back: "Encyclopedia",
    cats: { gems: "Gems", uniques: "Uniques", bases: "Base types", currency: "Currency" },
    catLede: {
      gems: "Skill, support and spirit gems, with their stats at every level.",
      uniques: "Every unique with its modifiers and what it sells for.",
      bases: "Weapons, armour, jewellery and flasks, with their base stats.",
      currency: "Orbs, runes, soul cores, omens and the rest of the currency.",
    },
    gemKinds: { active: "Skill", support: "Support", spirit: "Spirit" },
    colors: { str: "Strength", dex: "Dexterity", int: "Intelligence", none: "Other" },
    groups: { weapon: "Weapons", armour: "Armour", jewellery: "Jewellery", flask: "Flasks" },
    level: "Level",
    gemLevel: (n: number) => `Gem level ${n}`,
    castTime: "Cast time",
    seconds: (s: string) => `${s} sec`,
    lineage: "Lineage support",
    recommended: "Recommended supports",
    perLevel: "Every level",
    atLevel: "At level",
    reqLevel: "Requires level",
    requires: "Requires",
    attrs: { strength: "Str", dexterity: "Dex", intelligence: "Int" },
    dropLevel: "Drop level",
    size: "Size",
    props: {
      armour: "Armour",
      evasion: "Evasion Rating",
      energy_shield: "Energy Shield",
      block: "Block chance",
      physical: "Physical Damage",
      crit: "Critical Hit Chance",
      aps: "Attacks per Second",
      range: "Weapon Range",
      reload: "Reload Time",
      spirit: "Spirit",
      charges: "Charges",
      perUse: "Consumes {0} of {1} Charges on use",
      recovers: "Recovers {0} over {1} seconds",
      life: "Life",
      mana: "Mana",
    },
    basedOn: "Base type",
    onThisBase: "Uniques on this base",
    price: "Price",
    priceIn: (league: string) => `In ${league}`,
    seeEconomy: "See it in the economy",
    stack: "Stack size",
    socketed: "When socketed in",
    corrupted: "Corrupted",
    noMods: "We don't have this unique's modifiers yet: it hasn't been listed for sale this league.",
    fromGame: "Names, texts and art are the game's own. Stats from the current version.",
    englishOnly: "",
    patches: "Patch notes",
  },
  pat: {
    title: "Patch notes",
    lede: "Every patch, patch by patch: what went up, what went down and what got fixed.",
    loading: "Opening the journal…",
    notFound: "We don't have that patch.",
    latest: "Latest patch",
    archive: "The archive",
    content: "Content update",
    patch: "Patch",
    hotfixes: "Hotfixes",
    lines: (n: number) => `${n} changes`,
    up: "Buffs",
    down: "Nerfs",
    fix: "Fixes",
    new: "New",
    all: "All",
    filter: "Show",
    official: "Official notes",
    noSpanish: "",
    touches: "What it touches",
    toc: "Sections",
    onlyEnglishHotfix: "",
  },
};

const ES: typeof EN = {
  enc: {
    title: "Enciclopedia",
    lede: "Cada gema, único, base y moneda del juego, como la muestra el juego.",
    loading: "Abriendo la enciclopedia…",
    notFound: "Eso no está en la enciclopedia.",
    search: "Buscar en toda la enciclopedia…",
    searchCat: "Buscar en esta categoría…",
    noResults: "No hay nada con ese nombre.",
    count: (n: number) => `${n} entradas`,
    all: "Todas",
    back: "Enciclopedia",
    cats: { gems: "Gemas", uniques: "Únicos", bases: "Bases", currency: "Monedas" },
    catLede: {
      gems: "Gemas de habilidad, de apoyo y de espíritu, con sus números en cada nivel.",
      uniques: "Todos los únicos con sus modificadores y lo que valen.",
      bases: "Armas, armaduras, joyería y frascos, con sus propiedades base.",
      currency: "Orbes, runas, núcleos de alma, presagios y el resto de las monedas.",
    },
    gemKinds: { active: "Habilidad", support: "Apoyo", spirit: "Espíritu" },
    colors: { str: "Fuerza", dex: "Destreza", int: "Inteligencia", none: "Otras" },
    groups: { weapon: "Armas", armour: "Armaduras", jewellery: "Joyería", flask: "Frascos" },
    level: "Nivel",
    gemLevel: (n: number) => `Nivel de gema ${n}`,
    castTime: "Tiempo de lanzamiento",
    seconds: (s: string) => `${s} s`,
    lineage: "Apoyo de linaje",
    recommended: "Apoyos recomendados",
    perLevel: "Nivel por nivel",
    atLevel: "En el nivel",
    reqLevel: "Requiere nivel",
    requires: "Requiere",
    attrs: { strength: "Fue", dexterity: "Des", intelligence: "Int" },
    dropLevel: "Nivel de aparición",
    size: "Tamaño",
    props: {
      armour: "Armadura",
      evasion: "Evasión",
      energy_shield: "Escudo de energía",
      block: "Probabilidad de bloqueo",
      physical: "Daño físico",
      crit: "Probabilidad de golpe crítico",
      aps: "Ataques por segundo",
      range: "Alcance del arma",
      reload: "Tiempo de recarga",
      spirit: "Espíritu",
      charges: "Cargas",
      perUse: "Consume {0} de {1} cargas al usarse",
      recovers: "Recupera {0} en {1} segundos",
      life: "vida",
      mana: "maná",
    },
    basedOn: "Base",
    onThisBase: "Únicos sobre esta base",
    price: "Precio",
    priceIn: (league: string) => `En ${league}`,
    seeEconomy: "Verlo en la economía",
    stack: "Tamaño de la pila",
    socketed: "Engarzado en",
    corrupted: "Corrupto",
    noMods: "Todavía no tenemos los modificadores de este único: nadie lo publicó a la venta esta liga.",
    fromGame: "Los nombres, textos y dibujos son los del juego. Números de la versión actual.",
    englishOnly: "",
    patches: "Notas de parche",
  },
  pat: {
    title: "Parches",
    lede: "Cada parche, uno por uno: qué subió, qué bajó y qué se arregló.",
    loading: "Abriendo el diario…",
    notFound: "No tenemos ese parche.",
    latest: "Último parche",
    archive: "La hemeroteca",
    content: "Actualización de contenido",
    patch: "Parche",
    hotfixes: "Hotfixes",
    lines: (n: number) => `${n} cambios`,
    up: "Mejoras",
    down: "Nerfeos",
    fix: "Arreglos",
    new: "Nuevo",
    all: "Todo",
    filter: "Mostrar",
    official: "Notas oficiales",
    noSpanish: "Este parche no tiene traducción oficial: se muestra en inglés.",
    touches: "Lo que toca",
    toc: "Secciones",
    onlyEnglishHotfix: "Este hotfix sólo salió en inglés.",
  },
};

const P2 = { en: EN, es: ES };
/** Para el build (migas de pan del prerender), que no puede usar el hook. */
export const POE2_COPY = P2;
export const usePoe2Copy = () => P2[useLang().lang];
export type Poe2Copy = typeof EN;
