"""
Para qué sirve lo que el juego no dice, cada cosa con la página de la wiki (o
la fuente) de donde sale.

Pedido de ZoTaD (2026-09-28): "Se usa en" sólo ve recetas y piezas, así que
una llave, un cohete o un festín parecían no servir para nada. Lo que el juego
sí trae (qué se planta, qué come cada animal, las sillas, lo que se vende, los
trofeos) lo calcula `site.py`; acá va el resto, redactado con palabras propias.

Cada entrada es `{"kind": "text", "text": {"en", "es"}}`, con `ref` opcional
(el id de lo que se nombra, para enlazarlo).
"""

PURPOSES: dict[str, list[dict]] = {
    # https://valheim.weirdgloop.org/w/Coins
    'Coins': [{"kind": "text", "text": {"en": "The game's currency: spend it at Haldor, Hildir and the Bog Witch to buy their goods; you get more by selling valuables to them.", "es": "Es la moneda del juego: gástala con Haldor, Hildir y la bruja del pantano para comprar lo que venden; consigues más vendiéndoles objetos de valor."}}, {"kind": "text", "text": {"en": "It is also the material for decorative builds: Coin Pile, Coin Stack and Treasure Chest.", "es": "También es el material de piezas decorativas: Pila de monedas, Montón de monedas y Cofre de tesoros."}}],
    # Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): itemstand m_supportedItems
    'AncientCoin': [{"kind": "text", "text": {"en": "It can also be hung on an Item Stand as decoration.", "es": "También puedes colgarla en un Expositor como decoración."}}],
    # https://valheim.weirdgloop.org/w/Feast ; data/items.json food values
    'FeastMeadows_Material': [{"kind": "text", "text": {"en": "Place it with the Serving Tray to set out a shared feast with 10 servings; each serving gives 35 health, 35 stamina and heals 2 HP per tick for 50 minutes.", "es": "Colócalo con la Bandeja para servir y queda un banquete compartido de 10 porciones; cada porción da 35 de salud, 35 de aguante y cura 2 por tic durante 50 minutos."}}],
    # https://valheim.weirdgloop.org/w/Feast ; data/items.json food values
    'FeastBlackforest_Material': [{"kind": "text", "text": {"en": "Place it with the Serving Tray to set out a shared feast with 10 servings; each serving gives 35 health, 35 stamina and heals 3 HP per tick for 50 minutes.", "es": "Colócalo con la Bandeja para servir y queda un banquete compartido de 10 porciones; cada porción da 35 de salud, 35 de aguante y cura 3 por tic durante 50 minutos."}}],
    # https://valheim.weirdgloop.org/w/Feast ; data/items.json food values
    'FeastSwamps_Material': [{"kind": "text", "text": {"en": "Place it with the Serving Tray to set out a shared feast with 10 servings; each serving gives 35 health, 35 stamina and heals 3 HP per tick for 50 minutes.", "es": "Colócalo con la Bandeja para servir y queda un banquete compartido de 10 porciones; cada porción da 35 de salud, 35 de aguante y cura 3 por tic durante 50 minutos."}}],
    # https://valheim.weirdgloop.org/w/Feast ; data/items.json food values
    'FeastOceans_Material': [{"kind": "text", "text": {"en": "Place it with the Serving Tray to set out a shared feast with 10 servings; each serving gives 45 health, 45 stamina and heals 3 HP per tick for 50 minutes.", "es": "Colócalo con la Bandeja para servir y queda un banquete compartido de 10 porciones; cada porción da 45 de salud, 45 de aguante y cura 3 por tic durante 50 minutos."}}],
    # https://valheim.weirdgloop.org/w/Feast ; data/items.json food values
    'FeastMountains_Material': [{"kind": "text", "text": {"en": "Place it with the Serving Tray to set out a shared feast with 10 servings; each serving gives 45 health, 45 stamina and heals 3 HP per tick for 50 minutes.", "es": "Colócalo con la Bandeja para servir y queda un banquete compartido de 10 porciones; cada porción da 45 de salud, 45 de aguante y cura 3 por tic durante 50 minutos."}}],
    # https://valheim.weirdgloop.org/w/Feast ; data/items.json food values
    'FeastPlains_Material': [{"kind": "text", "text": {"en": "Place it with the Serving Tray to set out a shared feast with 10 servings; each serving gives 55 health, 55 stamina and heals 4 HP per tick for 50 minutes.", "es": "Colócalo con la Bandeja para servir y queda un banquete compartido de 10 porciones; cada porción da 55 de salud, 55 de aguante y cura 4 por tic durante 50 minutos."}}],
    # https://valheim.weirdgloop.org/w/Feast ; data/items.json food values
    'FeastMistlands_Material': [{"kind": "text", "text": {"en": "Place it with the Serving Tray to set out a shared feast with 10 servings; each serving gives 65 health, 65 stamina, 33 eitr and heals 5 HP per tick for 50 minutes.", "es": "Colócalo con la Bandeja para servir y queda un banquete compartido de 10 porciones; cada porción da 65 de salud, 65 de aguante, 33 de eitr y cura 5 por tic durante 50 minutos."}}],
    # https://valheim.weirdgloop.org/w/Feast ; data/items.json food values
    'FeastAshlands_Material': [{"kind": "text", "text": {"en": "Place it with the Serving Tray to set out a shared feast with 10 servings; each serving gives 75 health, 75 stamina, 38 eitr and heals 6 HP per tick for 50 minutes.", "es": "Colócalo con la Bandeja para servir y queda un banquete compartido de 10 porciones; cada porción da 75 de salud, 75 de aguante, 38 de eitr y cura 6 por tic durante 50 minutos."}}],
    # https://valheim.weirdgloop.org/w/Feast ; data/items.json food values
    'FeastDeepNorth_Material': [{"kind": "text", "text": {"en": "Place it with the Serving Tray to set out a shared feast with 10 servings; each serving gives 85 health, 85 stamina, 43 eitr and heals 7 HP per tick for 50 minutes.", "es": "Colócalo con la Bandeja para servir y queda un banquete compartido de 10 porciones; cada porción da 85 de salud, 85 de aguante, 43 de eitr y cura 7 por tic durante 50 minutos."}}],
    # https://valheim.weirdgloop.org/w/Asksvin#Breeding ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): EggGrow AsksvinEgg m_growTime=1800 m_requireNearbyFire=1 m_grownPrefab=Asksvin_hatchling m_tamed=1
    'AsksvinEgg': [{"kind": "text", "text": {"en": "Leave it on the ground by itself (not in a stack) next to a fire: after 30 minutes it hatches into an already tamed Asksvin Hatchling, which grows into an Asksvin. The egg's quality (1 to 3) sets the hatchling's stars.", "es": "Déjalo solo en el suelo (no en pila) junto a un fuego: a los 30 minutos nace una Cría de cenicerdo ya domesticada, que crece hasta ser un Cenicerdo. La calidad del huevo (1 a 3) marca las estrellas de la cría."}}],
    # https://valheim.weirdgloop.org/w/Bloodgold_Payload ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): Catapult m_includeItemsOverride
    'Catapult_Ammo_BloodGold': [{"kind": "text", "text": {"en": "Catapult ammunition: load it into the bucket and it is launched, exploding on impact for 200 pure, 200 chop and 600 pickaxe damage in a 2 m radius. The strongest payload, made to smash structures.", "es": "Munición para la Catapulta: al ponerla en el cubo sale disparada y estalla al impactar con 200 de daño puro, 200 de tala y 600 de pico en 2 m de radio. Es la carga más fuerte, pensada para derribar estructuras."}}],
    # https://valheim.weirdgloop.org/w/Explosive_Payload ; https://valheim.weirdgloop.org/w/Catapult
    'BombSiege': [{"kind": "text", "text": {"en": "Catapult ammunition: once loaded it is launched and explodes for 100 pure, 100 chop and 400 pickaxe damage in a 3 m radius, and can dig into the terrain. Used to break Charred Fortress walls and gates and the Effigies of Malice behind them.", "es": "Munición para la Catapulta: al cargarla sale disparada y estalla con 100 de daño puro, 100 de tala y 400 de pico en 3 m de radio, y puede abrir el terreno. Sirve para romper muros y portones de la Fortaleza carbonizada y las Efigies de malicia que hay detrás."}}],
    # https://valheim.weirdgloop.org/w/Grausten_Payload ; https://valheim.weirdgloop.org/w/Catapult ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): Catapult m_defaultAmmo=Catapult_ammo
    'Catapult_ammo': [{"kind": "text", "text": {"en": "The Catapult's basic ammunition: it hits for 20 blunt plus a small 5 blunt, 5 chop and 5 pickaxe blast in 3 m. It is cheap and very accurate, so it is mostly used to find your aim before firing stronger payloads.", "es": "La munición básica de la Catapulta: golpea con 20 de contundente más una pequeña explosión de 5 de contundente, 5 de tala y 5 de pico en 3 m. Es barata y muy precisa, así que se usa sobre todo para afinar la puntería antes de lanzar cargas más fuertes."}}],
    # https://valheim.weirdgloop.org/w/Fireworks ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): Fireplace m_fireworkItemList
    'FireworksRocket_Blue': [{"kind": "text", "text": {"en": "Use it on a lit fire (Campfire, Bonfire and similar) and it shoots into the sky and bursts in blue light. It is purely decorative.", "es": "Úsalo sobre un fuego encendido (Fogata, Hoguera y similares) y sale disparado al cielo para estallar en luces de color azul. Es puramente decorativo."}}],
    # https://valheim.weirdgloop.org/w/Fireworks ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): Fireplace m_fireworkItemList
    'FireworksRocket_Cyan': [{"kind": "text", "text": {"en": "Use it on a lit fire (Campfire, Bonfire and similar) and it shoots into the sky and bursts in cyan light. It is purely decorative.", "es": "Úsalo sobre un fuego encendido (Fogata, Hoguera y similares) y sale disparado al cielo para estallar en luces de color cian. Es puramente decorativo."}}],
    # https://valheim.weirdgloop.org/w/Fireworks ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): Fireplace m_fireworkItemList
    'FireworksRocket_Green': [{"kind": "text", "text": {"en": "Use it on a lit fire (Campfire, Bonfire and similar) and it shoots into the sky and bursts in green light. It is purely decorative.", "es": "Úsalo sobre un fuego encendido (Fogata, Hoguera y similares) y sale disparado al cielo para estallar en luces de color verde. Es puramente decorativo."}}],
    # https://valheim.weirdgloop.org/w/Fireworks ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): Fireplace m_fireworkItemList
    'FireworksRocket_Purple': [{"kind": "text", "text": {"en": "Use it on a lit fire (Campfire, Bonfire and similar) and it shoots into the sky and bursts in purple light. It is purely decorative.", "es": "Úsalo sobre un fuego encendido (Fogata, Hoguera y similares) y sale disparado al cielo para estallar en luces de color morado. Es puramente decorativo."}}],
    # https://valheim.weirdgloop.org/w/Fireworks ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): Fireplace m_fireworkItemList
    'FireworksRocket_Red': [{"kind": "text", "text": {"en": "Use it on a lit fire (Campfire, Bonfire and similar) and it shoots into the sky and bursts in red light. It is purely decorative.", "es": "Úsalo sobre un fuego encendido (Fogata, Hoguera y similares) y sale disparado al cielo para estallar en luces de color rojo. Es puramente decorativo."}}],
    # https://valheim.weirdgloop.org/w/Fireworks ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): Fireplace m_fireworkItemList
    'FireworksRocket_Yellow': [{"kind": "text", "text": {"en": "Use it on a lit fire (Campfire, Bonfire and similar) and it shoots into the sky and bursts in yellow light. It is purely decorative.", "es": "Úsalo sobre un fuego encendido (Fogata, Hoguera y similares) y sale disparado al cielo para estallar en luces de color amarillo. Es puramente decorativo."}}],
    # Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): itemstand m_supportedItems
    'AncientGemstoneBlack': [{"kind": "text", "text": {"en": "It can also be hung on an Item Stand as decoration.", "es": "También puedes colgarla en un Expositor como decoración."}}],
    # Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): itemstand m_supportedItems
    'AncientGemstoneGreen': [{"kind": "text", "text": {"en": "It can also be hung on an Item Stand as decoration.", "es": "También puedes colgarla en un Expositor como decoración."}}],
    # Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): itemstand m_supportedItems
    'AncientGemstoneOrange': [{"kind": "text", "text": {"en": "It can also be hung on an Item Stand as decoration.", "es": "También puedes colgarla en un Expositor como decoración."}}],
    # Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): itemstand m_supportedItems
    'AncientGemstonePurple': [{"kind": "text", "text": {"en": "It can also be hung on an Item Stand as decoration.", "es": "También puedes colgarla en un Expositor como decoración."}}],
    # https://valheim.weirdgloop.org/w/Hildir's_Chests ; data/traders.json requiredKey Hildir1
    'chest_hildir1': [{"kind": "text", "text": {"en": "Bring it back to Hildir and hand it over: she unlocks simple dresses and tunics, the harvest outfits and three hats in her shop. It weighs 200 and only travels through a Stone Portal, not a regular Portal.", "es": "Llévalo a Hildir y entrégaselo: desbloquea en su tienda vestidos y túnicas sencillos, la ropa de cosecha y tres tocados. Pesa 200 y solo pasa por el Portal – Piedra, no por el Portal común."}}],
    # https://valheim.weirdgloop.org/w/Hildir's_Chests ; data/traders.json requiredKey Hildir2
    'chest_hildir2': [{"kind": "text", "text": {"en": "Bring it back to Hildir and hand it over: she unlocks shawl dresses, cape tunics and three headscarves and caps in her shop. It weighs 200 and only travels through a Stone Portal, not a regular Portal.", "es": "Llévalo a Hildir y entrégaselo: desbloquea en su tienda vestidos con manto, túnicas con capa y tres pañuelos y gorros. Pesa 200 y solo pasa por el Portal – Piedra, no por el Portal común."}}],
    # https://valheim.weirdgloop.org/w/Hildir's_Chests ; data/traders.json requiredKey Hildir3
    'chest_hildir3': [{"kind": "text", "text": {"en": "Bring it back to Hildir and hand it over: she unlocks beaded dresses and tunics, three headscarves and caps, and Basic Fireworks (50 Coins each). It weighs 200 and only travels through a Stone Portal, not a regular Portal.", "es": "Llévalo a Hildir y entrégaselo: desbloquea vestidos y túnicas con abalorios, tres pañuelos y gorros, y el Cohete básico (50 Monedas cada uno). Pesa 200 y solo pasa por el Portal – Piedra, no por el Portal común."}}],
    # https://valheim.weirdgloop.org/w/Intricate_Key ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): Door Morkborg_gate m_consumeKey=0; Morkhalla_jotun_gate m_consumeKey=1 m_canNotBeClosed=1
    'BloodGoldKey': [{"kind": "text", "text": {"en": "Opens the Gates of Mörkhalla. At the entrance you only need to carry it and it is not used up; some gates inside the dungeon consume the key and then stay open for good.", "es": "Abre las Puertas de Mörkhalla. En la entrada basta con llevarla encima y no se gasta; algunas puertas dentro de la mazmorra sí la consumen y después quedan abiertas para siempre."}}],
    # https://valheim.weirdgloop.org/w/Liquid_Frost ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): piece_FrostFoundry m_fuelItem=FrozenFuel m_maxFuel=20 m_secPerFuel=10, cook time 50 s
    'FrozenFuel': [{"kind": "text", "text": {"en": "Fuel for the Frost Foundry: each cast you place in it burns 5 Liquid Frost over 50 seconds and hardens into the finished weapon, armor piece or Intricate Key. The foundry holds up to 20.", "es": "Combustible de la Forja de escarcha: cada pieza fundida que colocas gasta 5 de Escarcha líquida en 50 segundos y se endurece hasta ser el arma, la armadura o la Llave intrincada terminada. La forja admite hasta 20."}}],
    # https://valheim.weirdgloop.org/w/Memorial_Site ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): offeraltar_memorialsite (in NorthMemorialPlace) m_bossItem=MemorialCoal m_bossItems=3
    'MemorialCoal': [{"kind": "text", "text": {"en": "Offer 3 at the Ancient Altar of a Memorial Place in the Deep North to summon a hostile Fallen Warrior, which drops Frostfire Essence or Thunderblood Essence when killed.", "es": "Ofrece 3 en el Altar antiguo de un Lugar memorial del Norte profundo para invocar a un Guerrero caído hostil, que al morir suelta Esencia de fuego gélido o Esencia de sangre de trueno."}}],
    # https://valheim.weirdgloop.org/w/Sacrificial_Blood ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): ItemStand in StartTemple m_supportedItems=[FrozenKingDrop], name $stonecircle_hook_name
    'FrozenKingDrop': [{"kind": "text", "text": {"en": "Take it back to the Sacrificial Stones in the Meadows and place it on the Chiselled Platform: Hugin, Munin and a Valkyrie appear, and choosing 'Journey to Valhalla' with the Valkyrie ends the game.", "es": "Llévala a las Piedras de sacrificio de las Praderas y colócala en la Plataforma cincelada: aparecen Hugin, Munin y una Valquiria, y al elegir 'Viaje a Valhalla' con la Valquiria termina la partida."}}],
    # https://valheim.weirdgloop.org/w/Sealbreaker ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): dungeon_queen_door m_keyItem=DvergrKey m_consumeKey=0
    'DvergrKey': [{"kind": "text", "text": {"en": "Opens the sealed door of the Infested Citadel, the Queen's lair in the Mistlands; you only need it in your inventory and it is not used up.", "es": "Abre la puerta sellada de la Ciudadela infestada, la guarida de La Reina en las Tierras Nubladas; basta con tenerlo en el inventario y no se gasta."}}],
    # https://valheim.weirdgloop.org/w/Swamp_Key ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): sunken_crypt_gate m_keyItem=CryptKey m_consumeKey=0
    'CryptKey': [{"kind": "text", "text": {"en": "Opens the iron gates of the Sunken Crypts in the Swamp. It is never used up, so one key works for every crypt.", "es": "Abre los portones de hierro de las Criptas hundidas del Pantano. No se gasta nunca, así que una sola llave sirve para todas las criptas."}}],
    # https://valheim.weirdgloop.org/w/The_Prison ; Valheim 1.0 game files (installed build, read with UnityPy 2026-09-28): offeraltar_FrozenKing m_bossItem=HatefulBlood
    'HatefulBlood': [{"kind": "text", "text": {"en": "Offer 3 at the Strange Bowl beyond the Aesir Passage in the Deep North to summon Kall Fimbulbringer, the final boss; all three are used up at once and he appears 12 seconds later.", "es": "Ofrece 3 en el Cuenco extraño que hay tras el Pasaje de los Æsir, en el Norte profundo, para invocar a Kall Fimbulbringer, el jefe final; se gastan las tres a la vez y él aparece 12 segundos después."}}],
}
