/**
 * Los nombres de prefab de los lugares del juego (1.0), para traducir el hash
 * que guarda el `.db2`. Copiados de `games/valheim/data/map/locations.json`
 * (`prefabName`); `locationNames.test.ts` controla que sigan iguales.
 */
export const LOCATION_PREFABS: readonly string[] = [
  "AbandonedLogCabin02", "AbandonedLogCabin03", "AbandonedLogCabin04", "AncientUpgradeStation", "AshlandRuins",
  "BearCave", "BigRockClearing", "BogWitch_Camp", "Bonemass", "Castle", "CharredFortress", "CharredRuins1",
  "CharredRuins2", "CharredRuins3", "CharredRuins4", "CharredStone_Spawner", "CharredTowerRuins1",
  "CharredTowerRuins1_dvergr", "CharredTowerRuins2", "CharredTowerRuins3", "CombatRuin01", "Crypt2", "Crypt3",
  "Crypt4", "DevBedchamber", "DevCombatRange", "DevCombatRing", "DevDressingRoom", "DevFloor1", "DevForge",
  "DevGarden", "DevGround1", "DevGround2", "DevHouse1", "DevHouse2", "DevHouse3", "DevHouse4", "DevHouse5",
  "DevHouseStart", "DevKitchen", "DevMageRoom", "DevSoundTest", "DevWall1", "DevWall2", "DevWallAsh", "DN_Bossroom",
  "DN_gammeltrollFrac01", "DN_gammeltrollFrac02", "DN_hut01", "Dolmen01", "Dolmen02", "Dolmen03", "Dragonqueen",
  "DrakeLorestone", "DrakeNest01", "Eikthyrnir", "FaderLocation", "FimbulLocation01", "FireHole", "Fort1",
  "FortressRuins", "FrozenShip01_DN", "FrozenShip02_DN", "FrozenShip03_DN", "GDKing", "GoblinCamp1", "GoblinCamp2",
  "GoblinCamp2_1", "GoblinHut01", "GoblinHut02", "GoblinHut03", "GoblinKing", "Grave1", "Greydwarf_camp1",
  "Greydwarf_camp2", "Greydwarf_camp3", "HalfBurried_ForestCrypt", "Hildir_camp", "Hildir_cave", "Hildir_crypt",
  "Hildir_plainsfortress", "HotSpring1", "HotSpring2", "HotSpring3", "Hugintest", "IcePond1", "InfestedTree01",
  "LeviathanLava", "LumberCamp", "Mistlands_DvergrBossEntrance1", "Mistlands_DvergrTownEntrance1",
  "Mistlands_DvergrTownEntrance2", "Mistlands_Excavation1", "Mistlands_Excavation2", "Mistlands_Excavation3",
  "Mistlands_Giant1", "Mistlands_Giant2", "Mistlands_GuardTower1_new", "Mistlands_GuardTower1_ruined_new",
  "Mistlands_GuardTower1_ruined_new2", "Mistlands_GuardTower2_new", "Mistlands_GuardTower3_new",
  "Mistlands_GuardTower3_ruined_new", "Mistlands_Harbour1", "Mistlands_Lighthouse1_new", "Mistlands_RoadPost1",
  "Mistlands_RockSpire1", "Mistlands_Statue1", "Mistlands_Statue2", "Mistlands_StatueGroup1", "Mistlands_Swords1",
  "Mistlands_Swords2", "Mistlands_Swords3", "Mistlands_Viaduct1", "Mistlands_Viaduct2", "MorgenHole1", "MorgenHole2",
  "MorgenHole3", "MorkBorg", "MountainCave01", "MountainCave02", "MountainGrave01", "MountainWell1",
  "NorthMemorialPlace", "NorthVillage", "Pillar1", "Pillar2", "PlaceofMystery1", "PlaceofMystery2",
  "PlaceofMystery3", "Ruin1", "Ruin2", "Ruin3", "Runestone_Ashlands", "Runestone_BlackForest", "Runestone_Boars",
  "Runestone_DeepNorth", "Runestone_Draugr", "Runestone_Greydwarfs", "Runestone_Meadows", "Runestone_Mistlands",
  "Runestone_Mountains", "Runestone_Plains", "Runestone_Swamps", "ShipSetting01", "ShipSetting02", "ShipSetting03",
  "ShipWreck01", "ShipWreck01_DN", "ShipWreck02", "ShipWreck02_DN", "ShipWreck03", "ShipWreck04", "StartTemple",
  "StoneCircle", "StoneHenge1", "StoneHenge2", "StoneHenge3", "StoneHenge4", "StoneHenge5", "StoneHenge6",
  "StoneHouse1", "StoneHouse1_heath", "StoneHouse2", "StoneHouse2_heath", "StoneHouse3", "StoneHouse4",
  "StoneHouse5", "StoneHouse5_heath", "StoneTower1", "StoneTower2", "StoneTower3", "StoneTower4",
  "StoneTowerRuins03", "StoneTowerRuins04", "StoneTowerRuins05", "StoneTowerRuins05_leet", "StoneTowerRuins07",
  "StoneTowerRuins07_sunk", "StoneTowerRuins08", "StoneTowerRuins08_sunk", "StoneTowerRuins09",
  "StoneTowerRuins09_sunk", "StoneTowerRuins10", "StoneTowerRuins10_sunk", "SulfurArch", "SunkenCrypt1",
  "SunkenCrypt2", "SunkenCrypt3", "SunkenCrypt4", "SwampHut1", "SwampHut1_1", "SwampHut2", "SwampHut2_1",
  "SwampHut3", "SwampHut3_1", "SwampHut4", "SwampHut5", "SwampRuin1", "SwampRuin2", "SwampWell1", "TarPit1",
  "TarPit1_1", "TarPit2", "TarPit2_1", "TarPit3", "TarPit3_1", "TheDarkestHole", "TheHole01", "TrollCave",
  "TrollCave02", "Vendor_BlackForest", "VoltureNest", "Waymarker01", "Waymarker02", "WoodFarm1", "WoodHouse1",
  "WoodHouse10", "WoodHouse11", "WoodHouse12", "WoodHouse13", "WoodHouse2", "WoodHouse3", "WoodHouse4", "WoodHouse5",
  "WoodHouse6", "WoodHouse7", "WoodHouse8", "WoodHouse9", "WoodVillage1", "WoodVillage2", "xmastree",
];
