/**
 * Los textos del mapa interactivo de Valheim (2026-09-24), en los dos idiomas.
 * El título y la descripción para buscadores están en `valheimCopy.ts` (`map`),
 * porque los usa el prerender.
 */
import { useLang } from "../i18n";

const EN = {
  h1: "Valheim Interactive Map",
  lede: "Type your world seed and see the whole map: biomes, terrain, the bosses, dungeons, traders and every location, generated exactly like the game (1.0).",
  seed: "World seed",
  seedHint: "10 characters, as shown in the world list",
  go: "Show map",
  random: "Random seed",
  copy: "Copy link",
  copied: "Link copied",
  png: "Save image",
  layers: "Map",
  layer: { relief: "Terrain", biomes: "Biomes", height: "Height" } as Record<string, string>,
  grid: "Grid",
  locations: "Locations",
  count: (n: number) => `${n.toLocaleString("en")} locations`,
  search: "Search locations…",
  showAll: "Show all",
  hideAll: "Hide all",
  fromSpawn: "Distance from the spawn",
  spawn: "Spawn",
  goNearest: "Go to the nearest",
  summon: "summon with",
  inside: "Inside",
  found: "You find",
  chests: "In its chests",
  fromSpawnShort: "from the spawn",
  clickForMore: "Click for more",
  km: (m: number) => (m >= 1000 ? `${(m / 1000).toFixed(2)} km` : `${Math.round(m)} m`),
  all: "All",
  none: "None",
  generating: (p: number) => `Generating the world… ${Math.round(p * 100)}%`,
  generated: (s: number) => `World generated in ${s.toFixed(1)} s on your device`,
  placing: (p: number) => `Placing locations… ${Math.round(p * 100)}%`,
  placed: (n: number) => `${n.toLocaleString("en")} locations`,
  cursor: "Under the cursor",
  height: "height",
  water: "underwater",
  outside: "Outside the world",
  legend: "Biomes",
  candidates: "possible spots: the game keeps one, depending on where players explore first",
  coords: "Coordinates",
  distance: "from the center",
  openPage: "Open its page",
  close: "Close",
  noEngine: "The map could not be generated on this device.",
  howTitle: "How the map works",
  how: [
    "Valheim builds every world from its seed: the same seed always gives the same biomes, the same terrain and the same locations. This map reproduces the game's own world generator (version 1.0) in your browser, so nothing is uploaded anywhere.",
    "Drag to move, use the mouse wheel or pinch to zoom, and tap a location to see what it is. The link keeps your seed and the place you are looking at, so you can share it.",
    "Haldor, Hildir and the Bog Witch have several possible spots: the game picks one of them the first time a player gets close, so the map shows all of them.",
  ],
  findSeedTitle: "Where to find your seed",
  findSeed: [
    "In the world list when you start the game (it is under the world name), or in your server's settings.",
  ],
};

type MapCopy = typeof EN;

const ES: MapCopy = {
  h1: "Mapa interactivo de Valheim",
  lede: "Escribe la semilla de tu mundo y mira el mapa entero: biomas, relieve, jefes, mazmorras, comerciantes y todos los lugares, generados exactamente como en el juego (1.0).",
  seed: "Semilla del mundo",
  seedHint: "10 caracteres, como aparece en la lista de mundos",
  go: "Ver mapa",
  random: "Semilla al azar",
  copy: "Copiar enlace",
  copied: "Enlace copiado",
  png: "Guardar imagen",
  layers: "Mapa",
  layer: { relief: "Relieve", biomes: "Biomas", height: "Altura" },
  grid: "Cuadrícula",
  locations: "Lugares",
  count: (n) => `${n.toLocaleString("es")} lugares`,
  search: "Buscar lugares…",
  showAll: "Mostrar todo",
  hideAll: "Ocultar todo",
  fromSpawn: "Distancia desde el inicio",
  spawn: "Inicio",
  goNearest: "Ir al más cercano",
  summon: "se invoca con",
  inside: "Adentro",
  found: "Se encuentra",
  chests: "En sus cofres",
  fromSpawnShort: "del inicio",
  clickForMore: "Haz clic para ver más",
  km: (m) => (m >= 1000 ? `${(m / 1000).toFixed(2).replace(".", ",")} km` : `${Math.round(m)} m`),
  all: "Todos",
  none: "Ninguno",
  generating: (p) => `Generando el mundo… ${Math.round(p * 100)} %`,
  generated: (s) => `Mundo generado en ${s.toFixed(1).replace(".", ",")} s en tu dispositivo`,
  placing: (p) => `Ubicando lugares… ${Math.round(p * 100)} %`,
  placed: (n) => `${n.toLocaleString("es")} lugares`,
  cursor: "Bajo el cursor",
  height: "altura",
  water: "bajo el agua",
  outside: "Fuera del mundo",
  legend: "Biomas",
  candidates: "lugares posibles: el juego se queda con uno según dónde exploren primero los jugadores",
  coords: "Coordenadas",
  distance: "del centro",
  openPage: "Ver su ficha",
  close: "Cerrar",
  noEngine: "No se pudo generar el mapa en este dispositivo.",
  howTitle: "Cómo funciona el mapa",
  how: [
    "Valheim arma cada mundo a partir de su semilla: la misma semilla da siempre los mismos biomas, el mismo relieve y los mismos lugares. Este mapa reproduce el generador de mundos del propio juego (versión 1.0) en tu navegador, sin subir nada a ningún lado.",
    "Arrastra para moverte, usa la rueda del ratón o pellizca para hacer zoom y toca un lugar para ver qué es. El enlace guarda tu semilla y lo que estás mirando, así lo puedes compartir.",
    "Haldor, Hildir y la bruja del pantano tienen varios lugares posibles: el juego elige uno la primera vez que un jugador se acerca, por eso el mapa los muestra todos.",
  ],
  findSeedTitle: "Dónde encontrar tu semilla",
  findSeed: [
    "En la lista de mundos al empezar a jugar (está debajo del nombre del mundo) o en la configuración de tu servidor.",
  ],
};

export const useMapCopy = (): MapCopy => (useLang().lang === "es" ? ES : EN);
