/**
 * Textos del árbol de pasivas de PoE2 (2026-09-25), en los dos idiomas. El título
 * y la descripción para buscadores están en `i18n.ts` (`seo.poe2.tree`), porque
 * los usa el prerender.
 */
import { useLang } from "../i18n";

const EN = {
  h1: "Path of Exile 2 Passive Tree Planner",
  lede: "Plan your passive tree point by point and see it at every level, with your gems. Take it into the game with the Build Planner file.",
  loading: "Opening the passive tree…",
  failed: "The passive tree could not be loaded.",
  change: "Change",
  pickClass: "Choose your class",
  noAsc: "No ascendancy",
  soon: "Soon",
  points: (used: number, total: number) => `Passive points: ${used} / ${total}`,
  over: (n: number) => `${n} over the maximum`,
  asc: "Ascendancy",
  set1: "Set I",
  set2: "Set II",
  total: "Route",
  level: "Level",
  play: "Play the route",
  pause: "Pause",
  nextClicks: "Next clicks",
  both: "Both",
  search: "Search the tree…",
  matches: (n: number) => (n === 1 ? "1 node" : `${n} nodes`),
  ascBtn: "Ascendancy",
  home: "Center",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  tabs: { route: "Route", gems: "Gems", share: "Export" },
  routeHead: "Your route",
  empty: "Click a node near your class start: the shortest path is added to the route. Click a taken node to remove it.",
  band: (a: number, b: number) => `Levels ${a}–${b}`,
  nPoints: (n: number) => (n === 1 ? "1 point" : `${n} points`),
  noPoints: "No points left",
  trial: (n: number, lv: number) => `Trial ${n} · level ${lv}`,
  wsCycle: "Weapon set: click to change",
  dragHint: "Drag a row to reorder the route.",
  cantMove: "That order leaves a node unconnected.",
  clear: "Clear",
  confirmClear: "Clear the whole route?",
  confirmClass: "Changing class clears the route. Continue?",
  tip: {
    point: (n: number, lv: number) => `Point ${n} of the route · level ${lv}`,
    noPoints: "Beyond the available points",
    ascPoint: (n: number, lv: number) => `Ascendancy point ${n} · level ${lv}`,
    ascStart: "Ascendancy start",
    add: (n: number) => (n === 1 ? "Click: +1 point" : `Click: +${n} points`),
    remove: "Click: remove",
    none: "No effect",
    locked: "Needs its ascendancy node first",
    choose: "Take it and then choose one of its options, around it",
  },
  gems: {
    empty: "Add stages of levels and the skills you use in each one. They go into the game file too.",
    stage: (a: number, b: number) => `Levels ${a}–${b}`,
    from: "From",
    to: "to",
    addStage: "New stage",
    removeStage: "Remove stage",
    addSkill: "Add skill",
    addSupport: "Support",
    search: "Search a gem…",
    remove: "Remove",
    now: "Now",
    loading: "Loading gems…",
  },
  share: {
    how: "Download the file and put it in",
    folder: "Documents\\My Games\\Path of Exile 2\\BuildPlanner",
    how2: "In the game, open the passive tree and click the blue Build Planner icon at the top left: it marks every point at its level.",
    name: "Build name",
    download: "Download .build",
    import: "Import a .build",
    imported: (n: number) => `Imported ${n} passives.`,
    unknown: (n: number) => `${n} passives from another version of the tree were skipped.`,
    bad: "That file is not a build we can read.",
    link: "Or share the link: the whole route travels in the address, no account needed.",
    copy: "Copy link",
    copied: "Link copied",
    note: "Levels count one point per level and the 24 points from campaign quests at the level of their zone; ascendancy points arrive at the trials (22, 38, 60 and 75).",
  },
  howTitle: "How the planner works",
  how: [
    "The tree is the official one for the current version, with the game's own art. Click a node and the shortest path to it is added to your route, in order: that order is the order you take the points while levelling.",
    "The level bar shows the tree at any level: what you haven't reached yet is dimmed. Each point gets a level from one point per level plus the campaign quest points; points marked for a weapon set use the weapon set points instead.",
    "The Build Planner file (.build) is the one the game reads since 0.5: put it in its folder and the game highlights each node as you reach its level, and shows your gems for each stage.",
  ],
  fromGame: (v: string) => `Passive tree ${v}: nodes, texts and art are the game's own.`,
};

const ES: typeof EN = {
  h1: "Planificador del árbol de pasivas de Path of Exile 2",
  lede: "Armá tu árbol de pasivas punto por punto y mirá cómo queda en cada nivel, con tus gemas. Llevalo al juego con el archivo del Build Planner.",
  loading: "Abriendo el árbol de pasivas…",
  failed: "No se pudo cargar el árbol de pasivas.",
  change: "Cambiar",
  pickClass: "Elegí tu clase",
  noAsc: "Sin ascendencia",
  soon: "Pronto",
  points: (used, total) => `Puntos de pasiva: ${used} / ${total}`,
  over: (n) => `${n} de más`,
  asc: "Ascendencia",
  set1: "Set I",
  set2: "Set II",
  total: "Ruta",
  level: "Nivel",
  play: "Reproducir la ruta",
  pause: "Pausa",
  nextClicks: "Próximos clics",
  both: "Ambos",
  search: "Buscar en el árbol…",
  matches: (n) => (n === 1 ? "1 nodo" : `${n} nodos`),
  ascBtn: "Ascendencia",
  home: "Centrar",
  zoomIn: "Acercar",
  zoomOut: "Alejar",
  tabs: { route: "Ruta", gems: "Gemas", share: "Llevar al juego" },
  routeHead: "Tu ruta",
  empty: "Tocá un nodo cerca del inicio de tu clase: el camino más corto se suma a la ruta. Tocá uno tomado para sacarlo.",
  band: (a, b) => `Niveles ${a}–${b}`,
  nPoints: (n) => (n === 1 ? "1 punto" : `${n} puntos`),
  noPoints: "Sin puntos",
  trial: (n, lv) => `Prueba ${n} · nivel ${lv}`,
  wsCycle: "Set de armas: tocá para cambiarlo",
  dragHint: "Arrastrá una fila para cambiar el orden.",
  cantMove: "Ese orden deja un nodo sin conexión.",
  clear: "Borrar",
  confirmClear: "¿Borrar toda la ruta?",
  confirmClass: "Cambiar de clase borra la ruta. ¿Seguir?",
  tip: {
    point: (n, lv) => `Punto ${n} de la ruta · nivel ${lv}`,
    noPoints: "Más allá de los puntos que hay",
    ascPoint: (n, lv) => `Punto ${n} de ascendencia · nivel ${lv}`,
    ascStart: "Inicio de la ascendencia",
    add: (n) => (n === 1 ? "Clic: +1 punto" : `Clic: +${n} puntos`),
    remove: "Clic: sacar",
    none: "Sin efecto",
    locked: "Primero hace falta su nodo de ascendencia",
    choose: "Tomalo y después elegí una de sus opciones, alrededor",
  },
  gems: {
    empty: "Sumá tramos de niveles y las habilidades que usás en cada uno. También van al archivo del juego.",
    stage: (a, b) => `Niveles ${a}–${b}`,
    from: "Del",
    to: "al",
    addStage: "Nuevo tramo",
    removeStage: "Sacar tramo",
    addSkill: "Sumar habilidad",
    addSupport: "Soporte",
    search: "Buscar una gema…",
    remove: "Sacar",
    now: "Ahora",
    loading: "Cargando gemas…",
  },
  share: {
    how: "Descargá el archivo y ponelo en",
    folder: "Documentos\\My Games\\Path of Exile 2\\BuildPlanner",
    how2: "En el juego, abrí el árbol y tocá el ícono azul del Build Planner arriba a la izquierda: te marca cada punto en su nivel.",
    name: "Nombre de la build",
    download: "Descargar .build",
    import: "Importar un .build",
    imported: (n) => `Se importaron ${n} pasivos.`,
    unknown: (n) => `Se saltearon ${n} pasivos de otra versión del árbol.`,
    bad: "Ese archivo no es una build que podamos leer.",
    link: "O compartí el link: la ruta entera viaja en la dirección, sin cuentas.",
    copy: "Copiar link",
    copied: "Link copiado",
    note: "Los niveles cuentan un punto por nivel y los 24 de las misiones de la campaña en el nivel de su zona; los de ascendencia llegan en las pruebas (22, 38, 60 y 75).",
  },
  howTitle: "Cómo funciona el planificador",
  how: [
    "El árbol es el oficial de la versión actual, con el arte del juego. Tocá un nodo y el camino más corto hasta él se suma a tu ruta, en orden: ese orden es el orden en que tomás los puntos mientras subís de nivel.",
    "La barra de niveles muestra el árbol en cualquier nivel: lo que todavía no alcanzaste se ve apagado. Cada punto recibe un nivel contando uno por nivel más los puntos de las misiones de la campaña; los que marcás para un set de armas usan los puntos de set.",
    "El archivo del Build Planner (.build) es el que lee el juego desde la 0.5: ponelo en su carpeta y el juego te resalta cada nodo al llegar a su nivel, y te muestra las gemas de cada tramo.",
  ],
  fromGame: (v) => `Árbol de pasivas ${v}: nodos, textos y arte son los del juego.`,
};

export const useTreeCopy = () => (useLang().lang === "es" ? ES : EN);
export type TreeCopy = typeof EN;
