/**
 * Textos de la sección Valheim (2026-09-24).
 *
 * Aparte de `i18n.ts`, como `poe2Copy.ts`: son muchos y sólo los usa esta
 * sección. Donde el juego tiene su palabra, va la del juego (tabla
 * `localization` del cliente): "Tajante" y no "cortante" para el daño slash,
 * "Piquetes" para los atgeirs, los nombres de los biomas tal cual.
 */
import { useLang } from "./i18n";
import type { ValheimTab } from "./route";
import type { BiomeId } from "./valheimData";

const EN = {
  seo: {
    home: {
      title: "Valheim encyclopedia: recipes, food, meads, weapons and bosses | Vestigo",
      description: "Every recipe, food, mead, weapon, armor piece, building piece and creature in Valheim 1.0, with official names in English and Spanish and where each thing comes from.",
    },
    tab: (tab: string) => `Valheim ${tab.toLowerCase()}: full list with filters | Vestigo`,
    detail: (name: string, tab: string) => `${name} — Valheim ${tab.toLowerCase()} | Vestigo`,
    detailDesc: (name: string) => `${name} in Valheim: recipe, stats, where it comes from and what it is used for, straight from the game files.`,
  },
  title: "Valheim",
  lede: "Everything the game lets you make, eat, build and hunt — with the official names and where each thing comes from.",
  loading: "Opening the chest…",
  notFound: "That isn't in the encyclopedia.",
  search: "Search everything…",
  searchTab: "Search this tab…",
  noResults: "Nothing matches.",
  clear: "Clear filters",
  filtersTitle: "Filters",
  count: (n: number, total: number) => (n === total ? `${total}` : `${n} of ${total}`),
  fromGame: "Names, numbers and pictures come from the game files (Valheim 1.0). Valheim is a game by Iron Gate; Vestigo is not affiliated with it.",
  tabs: {
    foods: "Food", meads: "Meads", weapons: "Weapons", armor: "Armor", tools: "Tools",
    building: "Building", materials: "Materials", creatures: "Creatures", biomes: "Biomes", bosses: "Bosses",
  } as Record<ValheimTab, string>,
  tabLede: {
    foods: "Everything you can eat: what it gives, how long it lasts and how to cook it.",
    meads: "From the base at the mead ketill to the fermenter: what every mead needs and what it does.",
    weapons: "Every weapon, its damage, and what each upgrade costs.",
    armor: "Helmets, chests, legs, capes, shields and trinkets, with their armor and sets.",
    tools: "Tools, arrows, bolts and the rest of the ammo.",
    building: "Everything the hammer, the hoe, the cultivator and the serving tray can place, and what it takes.",
    materials: "Every material and trophy, where it comes from and what it is for.",
    creatures: "Every creature: health, what hurts it, what it drops and where it lives.",
    biomes: "The nine biomes in order: what lives there, what you find, what to bring and who rules it.",
    bosses: "The Forsaken: how to summon them, what hurts them and the power they leave.",
  } as Record<ValheimTab, string>,
  biomes: {
    meadows: "Meadows", blackforest: "Black Forest", swamp: "Swamp", mountain: "Mountain", plains: "Plains",
    ocean: "Ocean", mistlands: "Mistlands", ashlands: "Ashlands", deepnorth: "Deep North",
  } as Record<BiomeId, string>,
  damage: {
    blunt: "Blunt", slash: "Slash", pierce: "Pierce", fire: "Fire", frost: "Frost", lightning: "Lightning",
    poison: "Poison", spirit: "Spirit", chop: "Chop", pickaxe: "Pickaxe", damage: "Damage",
  } as Record<string, string>,
  weaponCls: {
    sword: "Swords", knife: "Knives", club: "Clubs", polearm: "Polearms", spear: "Spears", axe: "Axes", bow: "Bows",
    crossbow: "Crossbows", elemental: "Elemental Magic", blood: "Blood Magic", fists: "Fists", pickaxe: "Pickaxes", other: "Other",
  } as Record<string, string>,
  slot: {
    helmet: "Helmet", chest: "Chest", legs: "Legs", cape: "Cape", shield: "Shield", utility: "Utility", trinket: "Trinket", other: "Other",
  } as Record<string, string>,
  toolKind: { tool: "Tools", arrow: "Arrows", bolt: "Bolts", ammo: "Other ammo" } as Record<string, string>,
  focus: { health: "Health", stamina: "Stamina", eitr: "Eitr", balanced: "Balanced" } as Record<string, string>,
  effect: { health: "Healing", stamina: "Stamina", eitr: "Eitr", resist: "Resistance", other: "Other" } as Record<string, string>,
  how: {
    drop: "Hunting", pickable: "Picking", mine: "Mining", tree: "Chopping", destructible: "Breaking things", fish: "Fishing",
    chest: "In chests", location: "In dungeons", farm: "Farming", trader: "Buying", craft: "Crafting", convert: "Processing",
  } as Record<string, string>,
  tool: { Hammer: "Hammer", Hoe: "Hoe", Cultivator: "Cultivator", Feaster: "Serving tray" } as Record<string, string>,
  filters: {
    biome: "Biome", station: "Made at", focus: "Focus", effect: "Effect", cls: "Class", dmg: "Main damage", slot: "Slot",
    set: "Set", kind: "Type", tool: "Tool", category: "Category", comfort: "Comfort only", how: "How to get it",
    usedFor: "Used for", type: "Type", weak: "Weak to", all: "All", anywhere: "Anywhere", noStation: "No station",
    boss: "Bosses", normal: "Creatures", trophy: "Trophies", material: "Materials", noSet: "No set",
  },
  cols: {
    name: "Name", hp: "Health", st: "Stamina", eitr: "Eitr", min: "Lasts", station: "Made at", biome: "Biome",
    dmg: "Damage", cls: "Class", quality: "Max. quality", armor: "Armor", slot: "Slot", set: "Set", effect: "Effect",
    base: "Base", comfort: "Comfort", tool: "Tool", category: "Category", how: "How", usedFor: "Used for",
    health: "Health", weak: "Weak to", biomes: "Biomes", weight: "Weight",
  },
  minutes: (n: number) => `${n} min`,
  level: (n: number) => `level ${n}`,
  detail: {
    back: (tab: string) => `← ${tab}`,
    recipe: "Recipe",
    madeAt: "Made at",
    makes: (n: number) => `Makes ${n}`,
    upgrades: "Upgrades",
    upgradeTo: (q: number) => `Quality ${q}`,
    sources: "Where it comes from",
    usedIn: "Used in",
    noSources: "The game gives no fixed source for this one.",
    food: "Food",
    duration: "Lasts",
    regen: "Health regen",
    perSecond: (n: number) => `${n}/s`,
    damage: "Damage",
    perLevel: "Per quality level",
    armor: "Armor",
    block: "Block",
    weight: "Weight",
    stack: "Stack",
    comfort: "Comfort",
    chain: "How it's brewed",
    ferment: (min: number) => `${min} min`,
    yields: (n: number) => `×${n}`,
    chance: (p: string) => `${p}`,
    from: {
      craft: "Crafted", convert: "Processed", drop: "Dropped by", gather: "Found", farm: "Grown", trader: "Sold by",
    } as Record<string, string>,
    price: (n: number) => `${n} coins`,
    noBiome: "in dungeons and ruins",
    prev: "Previous",
    next: "Next",
    other: (name: string) => `In Spanish: ${name}`,
  },
  guide: {
    health: "Health",
    weak: "Weak to",
    resist: "Resistant to",
    immune: "Immune to",
    drops: "Drops",
    lives: "Lives in",
    boss: "Boss",
    env: "Weather",
    envFreezing: "Freezing: you need frost resistance (a mead or the right armor) or you will lose health.",
    envCold: "Cold: stay warm near fire, dry and rested.",
    envColdNight: "Cold at night.",
    envWet: "Rain makes you wet: stamina regenerates slower until you dry off.",
    envNone: "No weather effects that hurt you by themselves.",
    creatures: "Creatures",
    resources: "Resources",
    foods: "Best food made here",
    gear: "Made with what you find here",
    gearCount: (w: number, a: number, f: number) => `${w} weapons · ${a} armor pieces · ${f} foods`,
    tips: "Hugin says",
    summon: "How to summon",
    summonAt: (n: number, item: string) => `Offer ${n} × ${item} at the altar`,
    summonWhere: "Where to get the offering",
    power: "Forsaken Power",
    cooldown: (s: number) => `Cooldown ${Math.round(s / 60)} min`,
    biome: "Biome",
    open: "Open",
    step: (n: number) => `${n}`,
  },
};

const ES: typeof EN = {
  seo: {
    home: {
      title: "Valheim en español: recetas, comidas, hidromieles, armas y jefes | Vestigo",
      description: "Todas las recetas, comidas, hidromieles, armas, armaduras, construcciones y criaturas de Valheim 1.0, con los nombres oficiales en español e inglés y de dónde sale cada cosa.",
    },
    tab: (tab) => `${tab} de Valheim: la lista completa con filtros | Vestigo`,
    detail: (name, tab) => `${name} — ${tab} de Valheim | Vestigo`,
    detailDesc: (name) => `${name} en Valheim: receta, estadísticas, de dónde sale y para qué sirve, sacado de los archivos del juego.`,
  },
  title: "Valheim",
  lede: "Todo lo que el juego te deja fabricar, comer, construir y cazar, con los nombres oficiales y de dónde sale cada cosa.",
  loading: "Abriendo el cofre…",
  notFound: "Eso no está en la enciclopedia.",
  search: "Buscar en todo…",
  searchTab: "Buscar en esta pestaña…",
  noResults: "No hay nada con ese nombre.",
  clear: "Limpiar filtros",
  filtersTitle: "Filtros",
  count: (n, total) => (n === total ? `${total}` : `${n} de ${total}`),
  fromGame: "Nombres, números e imágenes salen de los archivos del juego (Valheim 1.0). Valheim es un juego de Iron Gate; Vestigo no está afiliado.",
  tabs: {
    foods: "Comidas", meads: "Hidromieles", weapons: "Armas", armor: "Armaduras", tools: "Herramientas",
    building: "Construcción", materials: "Materiales", creatures: "Criaturas", biomes: "Biomas", bosses: "Jefes",
  },
  tabLede: {
    foods: "Todo lo que se come: cuánto da, cuánto dura y cómo se cocina.",
    meads: "De la malta en el caldero de aguamiel al fermentador: qué lleva cada hidromiel y qué hace.",
    weapons: "Cada arma, su daño y lo que cuesta cada mejora.",
    armor: "Cascos, pecheras, grebas, capas, escudos y abalorios, con su armadura y su set.",
    tools: "Herramientas, flechas, virotes y el resto de la munición.",
    building: "Todo lo que ponen el martillo, la azada, el cultivador y la bandeja, y lo que cuesta.",
    materials: "Cada material y trofeo, de dónde sale y para qué sirve.",
    creatures: "Cada criatura: vida, qué le hace daño, qué suelta y dónde vive.",
    biomes: "Los nueve biomas en orden: qué vive ahí, qué encuentras, qué llevar y quién manda.",
    bosses: "Los Desterrados: cómo invocarlos, qué les pega y el poder que dejan.",
  },
  biomes: {
    meadows: "Praderas", blackforest: "Bosque negro", swamp: "Pantano", mountain: "Montaña", plains: "Llanuras",
    ocean: "Océano", mistlands: "Tierras Nubladas", ashlands: "Tierra de Ceniza", deepnorth: "Norte profundo",
  },
  damage: {
    blunt: "Contundente", slash: "Tajante", pierce: "Perforante", fire: "Fuego", frost: "Escarcha", lightning: "Rayo",
    poison: "Veneno", spirit: "Espíritu", chop: "Cortante", pickaxe: "Pico", damage: "Daño",
  },
  weaponCls: {
    sword: "Espadas", knife: "Cuchillos", club: "Garrotes", polearm: "Piquetes", spear: "Lanzas", axe: "Hachas", bow: "Arcos",
    crossbow: "Ballestas", elemental: "Magia elemental", blood: "Magia de sangre", fists: "Desarmado", pickaxe: "Picos", other: "Otras",
  },
  slot: {
    helmet: "Casco", chest: "Pechera", legs: "Grebas", cape: "Capa", shield: "Escudo", utility: "Utilidad", trinket: "Abalorio", other: "Otro",
  },
  toolKind: { tool: "Herramientas", arrow: "Flechas", bolt: "Virotes", ammo: "Otra munición" },
  focus: { health: "Vida", stamina: "Aguante", eitr: "Eitr", balanced: "Equilibrada" },
  effect: { health: "Curación", stamina: "Aguante", eitr: "Eitr", resist: "Resistencia", other: "Otros" },
  how: {
    drop: "Cazando", pickable: "Recogiendo", mine: "Minando", tree: "Talando", destructible: "Rompiendo objetos", fish: "Pescando",
    chest: "En cofres", location: "En mazmorras", farm: "Cultivando", trader: "Comprando", craft: "Fabricando", convert: "Procesando",
  },
  tool: { Hammer: "Martillo", Hoe: "Azada", Cultivator: "Cultivador", Feaster: "Bandeja" },
  filters: {
    biome: "Bioma", station: "Dónde se hace", focus: "Enfoque", effect: "Efecto", cls: "Clase", dmg: "Daño principal", slot: "Parte",
    set: "Set", kind: "Tipo", tool: "Herramienta", category: "Categoría", comfort: "Sólo con confort", how: "Cómo se consigue",
    usedFor: "Se usa en", type: "Tipo", weak: "Débil a", all: "Todos", anywhere: "Todas", noStation: "Sin estación",
    boss: "Jefes", normal: "Criaturas", trophy: "Trofeos", material: "Materiales", noSet: "Sin set",
  },
  cols: {
    name: "Nombre", hp: "Vida", st: "Aguante", eitr: "Eitr", min: "Dura", station: "Dónde se hace", biome: "Bioma",
    dmg: "Daño", cls: "Clase", quality: "Calidad máx.", armor: "Armadura", slot: "Parte", set: "Set", effect: "Efecto",
    base: "Malta", comfort: "Confort", tool: "Herramienta", category: "Categoría", how: "Cómo", usedFor: "Se usa en",
    health: "Vida", weak: "Débil a", biomes: "Biomas", weight: "Peso",
  },
  minutes: (n) => `${n} min`,
  level: (n) => `nivel ${n}`,
  detail: {
    back: (tab) => `← ${tab}`,
    recipe: "Receta",
    madeAt: "Se hace en",
    makes: (n) => `Hace ${n}`,
    upgrades: "Mejoras",
    upgradeTo: (q) => `Calidad ${q}`,
    sources: "De dónde sale",
    usedIn: "Se usa en",
    noSources: "El juego no le da una fuente fija.",
    food: "Comida",
    duration: "Dura",
    regen: "Regeneración de vida",
    perSecond: (n) => `${n}/s`,
    damage: "Daño",
    perLevel: "Por nivel de calidad",
    armor: "Armadura",
    block: "Bloqueo",
    weight: "Peso",
    stack: "Pila",
    comfort: "Confort",
    chain: "Cómo se prepara",
    ferment: (min) => `${min} min`,
    yields: (n) => `×${n}`,
    chance: (p) => `${p}`,
    from: {
      craft: "Se fabrica", convert: "Se procesa", drop: "Lo suelta", gather: "Se encuentra", farm: "Se cultiva", trader: "Lo vende",
    },
    price: (n) => `${n} monedas`,
    noBiome: "en mazmorras y ruinas",
    prev: "Anterior",
    next: "Siguiente",
    other: (name) => `En inglés: ${name}`,
  },
  guide: {
    health: "Vida",
    weak: "Débil a",
    resist: "Resiste",
    immune: "Inmune a",
    drops: "Suelta",
    lives: "Vive en",
    boss: "Jefe",
    env: "Clima",
    envFreezing: "Congelante: necesitas resistencia a la escarcha (una hidromiel o la armadura adecuada) o vas a perder vida.",
    envCold: "Frío: mantente cerca del fuego, seco y descansado.",
    envColdNight: "De noche hace frío.",
    envWet: "La lluvia te moja: el aguante se recupera más lento hasta que te seques.",
    envNone: "Sin clima que te lastime por sí solo.",
    creatures: "Criaturas",
    resources: "Recursos",
    foods: "Las mejores comidas de aquí",
    gear: "Hecho con lo que encuentras aquí",
    gearCount: (w, a, f) => `${w} armas · ${a} piezas de armadura · ${f} comidas`,
    tips: "Hugin dice",
    summon: "Cómo invocarlo",
    summonAt: (n, item) => `Ofrece ${n} × ${item} en el altar`,
    summonWhere: "Dónde se consigue la ofrenda",
    power: "Poder de los Desterrados",
    cooldown: (s) => `Recarga de ${Math.round(s / 60)} min`,
    biome: "Bioma",
    open: "Abrir",
    step: (n) => `${n}`,
  },
};

export type ValheimCopy = typeof EN;
export const VALHEIM_COPY: Record<"en" | "es", ValheimCopy> = { en: EN, es: ES };
export const useValheimCopy = () => VALHEIM_COPY[useLang().lang];
