/**
 * Textos de la sección Valheim (2026-09-24).
 *
 * Aparte de `i18n.ts`, como `poe2Copy.ts`: son muchos y sólo los usa esta
 * sección. Donde el juego tiene su palabra, va la del juego (tabla
 * `localization` del cliente): "Tajante" y no "cortante" para el daño slash,
 * "Piquetes" para los atgeirs, los nombres de los biomas tal cual.
 */
import { useLang } from "./i18n";
import type { ValheimTab } from "./route";
import type { BiomeId } from "./valheimData";

const EN = {
  seo: {
    home: {
      title: "Valheim encyclopedia: recipes, food, meads, weapons and bosses | Vestigo",
      description: "Every recipe, food, mead, weapon, armor piece, building piece and creature in Valheim 1.0, with official names in English and Spanish and where each thing comes from.",
    },
    tab: (tab: string) => `Valheim ${tab.toLowerCase()}: full list with filters | Vestigo`,
    detail: (name: string, tab: string) => `${name} — Valheim ${tab.toLowerCase()} | Vestigo`,
    detailDesc: (name: string) => `${name} in Valheim: recipe, stats, where it comes from and what it is used for, straight from the game files.`,
  },
  title: "Valheim",
  lede: "Everything the game lets you make, eat, build and hunt — with the official names and where each thing comes from.",
  loading: "Opening the chest…",
  notFound: "That isn't in the encyclopedia.",
  search: "Search everything…",
  searchTab: "Search this tab…",
  noResults: "Nothing matches.",
  clear: "Clear filters",
  filtersTitle: "Filters",
  count: (n: number, total: number) => (n === total ? `${total}` : `${n} of ${total}`),
  fromGame: "Names, numbers, icons and biome art come from the game files (Valheim 1.0), checked against the Valheim Wiki. Valheim is a game by Iron Gate; Vestigo is not affiliated with it.",
  photoBy: (a: string | null) => (a ? `Photo: ${a} / Valheim Wiki` : "Photo: Valheim Wiki"),
  places: "Dungeons and places",
  inhabitants: "Who lives there",
  placeLoot: "In its chests",
  variant: "Variant",
  more: {
    tame: "Taming", tameTime: (m: number) => `Takes about ${m} min, kept fed and away from fights`, fed: (m: number) => `Stays fed for ${m} min`,
    eats: "Eats", startsTamed: "Already tame: no taming needed.", saddle: "Can be ridden with", commandable: "Follows you and obeys when you call it.",
    breed: "Breeding", breedMax: (n: number) => `Breeds while fewer than ${n} of its kind are nearby`,
    breedLove: (n: number) => `Needs to eat ${n} times to get pregnant`, breedTime: (s: number) => `Pregnancy: ${s} s`, offspring: "Offspring",
    spawns: "When and where it spawns", day: "Day", night: "Night", dayNight: "Day and night", after: "after defeating",
    group: (a: number, b: number) => (a === b ? (a > 1 ? `groups of ${a}` : "alone") : `groups of ${a}–${b}`),
    forestIn: "in forests", forestOut: "outside forests", ocean: "at sea", altitude: (m: number) => `above ${m} m`, weather: "weather",
    events: "Raids it shows up in", biomeEvents: "Raids by this biome's enemies", eventAfter: "from", eventUntil: "until",
    attacks: "Attacks", tips: "Tips", cooldown: (s: number) => `every ${s} s`,
    effects: "Effects", setBonus: (n: number | null | undefined) => (n ? `Set bonus (${n} pieces)` : "Set bonus"), setPieces: "Other pieces of the set",
    equip: "When equipped", consume: "When taken", resists: "Resistances", move: (p: number) => `${p > 0 ? "+" : ""}${p}% movement speed`,
    mod: { resistant: "Resistant", weak: "Weak", immune: "Immune", veryResistant: "Very resistant", veryWeak: "Very weak",
      slightlyResistant: "Slightly resistant", slightlyWeak: "Slightly weak" } as Record<string, string>,
    stat: {
      healthUpFront: (v: number) => `+${v} health instantly`, staminaUpFront: (v: number) => `+${v} stamina instantly`, eitrUpFront: (v: number) => `+${v} eitr instantly`,
      healthOverTime: (v: number) => `+${v} health over time`, staminaOverTime: (v: number) => `+${v} stamina over time`, eitrOverTime: (v: number) => `+${v} eitr over time`,
      healthRegenMultiplier: (v: number) => `Health regen ×${v}`, staminaRegenMultiplier: (v: number) => `Stamina regen ×${v}`, eitrRegenMultiplier: (v: number) => `Eitr regen ×${v}`,
      addMaxCarryWeight: (v: number) => `+${v} carry weight`, speedModifier: (v: number) => `${pct(v)} movement speed`, swimSpeedModifier: (v: number) => `${pct(v)} swim speed`,
      runStaminaDrainModifier: (v: number) => `${pct(v)} stamina used running`, jumpStaminaUseModifier: (v: number) => `${pct(v)} stamina used jumping`,
      attackStaminaUseModifier: (v: number) => `${pct(v)} stamina used attacking`, blockStaminaUseModifier: (v: number) => `${pct(v)} stamina used blocking`,
      dodgeStaminaUseModifier: (v: number) => `${pct(v)} stamina used dodging`, swimStaminaUseModifier: (v: number) => `${pct(v)} stamina used swimming`,
      sneakStaminaUseModifier: (v: number) => `${pct(v)} stamina used sneaking`, runStaminaUseModifier: (v: number) => `${pct(v)} stamina used running`,
      homeItemStaminaUseModifier: (v: number) => `${pct(v)} stamina used by tools`, noiseModifier: (v: number) => `${pct(v)} noise`,
      stealthModifier: (v: number) => `${pct(v)} stealth`, fallDamageModifier: (v: number) => `${pct(v)} fall damage`, maxMaxFallSpeed: () => "Slow fall",
      addArmor: (v: number) => `+${v} armor`, staggerModifier: (v: number) => `${pct(v)} stagger`, timedBlockBonus: (v: number) => `${pct(v)} parry bonus`,
      adrenalineModifier: (v: number) => `${pct(v)} adrenaline`, windRunStaminaModifier: (v: number) => `${pct(v)} stamina running with the wind`,
      damageModifier: (v: number) => `Damage ×${v}`, ttl: (v: number) => `Lasts ${Math.round(v / 60) >= 1 ? `${Math.round(v / 60)} min` : `${v} s`}`,
    } as Record<string, (v: number) => string>,
    skill: (name: string, v: number) => `${v > 0 ? "+" : ""}${v} ${name}`,
    damagePct: (type: string, v: number) => `${pct(v)} ${type} damage`,
    skills: { 1: "Swords", 2: "Knives", 3: "Clubs", 4: "Polearms", 5: "Spears", 6: "Blocking", 7: "Axes", 8: "Bows", 9: "Elemental magic",
      10: "Blood magic", 11: "Unarmed", 12: "Pickaxes", 13: "Woodcutting", 14: "Crossbows", 100: "Jump", 101: "Sneak", 102: "Run",
      103: "Swim", 104: "Fishing", 105: "Cooking", 106: "Farming", 107: "Crafting", 110: "Ride" } as Record<number, string>,
    env: { Rain: "rain", LightRain: "light rain", ThunderStorm: "thunderstorm", Misty: "mist" } as Record<string, string>,
  },
  placeResources: "What you find there",
  foundIn: "Where it shows up",
  allBiomes: "All",
  wikiCredit: "Places, habitats and photos of creatures and places:",
  wikiLicense: "under CC BY-SA 3.0 (the author of each photo shows when you hover it).",
  tabs: {
    foods: "Food", meads: "Meads", weapons: "Weapons", armor: "Armor", tools: "Tools",
    building: "Building", materials: "Materials", creatures: "Creatures", biomes: "Biomes", places: "Places", bosses: "Bosses",
  } as Record<ValheimTab, string>,
  tabLede: {
    foods: "Everything you can eat: what it gives, how long it lasts and how to cook it.",
    meads: "From the base at the mead ketill to the fermenter: what every mead needs and what it does.",
    weapons: "Every weapon, its damage, and what each upgrade costs.",
    armor: "Helmets, chests, legs, capes, shields and trinkets, with their armor and sets.",
    tools: "Tools, arrows, bolts and the rest of the ammo.",
    building: "Everything the hammer, the hoe, the cultivator and the serving tray can place, and what it takes.",
    materials: "Every material and trophy, where it comes from and what it is for.",
    creatures: "Every creature: health, what hurts it, what it drops and where it lives.",
    biomes: "The nine biomes in order: what lives there, what you find, what to bring and who rules it.",
    places: "Dungeons, ruins and landmarks of every biome: who lives inside and what you can find there.",
    bosses: "The Forsaken: how to summon them, what hurts them and the power they leave.",
  } as Record<ValheimTab, string>,
  biomes: {
    meadows: "Meadows", blackforest: "Black Forest", swamp: "Swamp", mountain: "Mountain", plains: "Plains",
    ocean: "Ocean", mistlands: "Mistlands", ashlands: "Ashlands", deepnorth: "Deep North",
  } as Record<BiomeId, string>,
  damage: {
    blunt: "Blunt", slash: "Slash", pierce: "Pierce", fire: "Fire", frost: "Frost", lightning: "Lightning",
    poison: "Poison", spirit: "Spirit", chop: "Chop", pickaxe: "Pickaxe", damage: "Damage",
  } as Record<string, string>,
  weaponCls: {
    sword: "Swords", knife: "Knives", club: "Clubs", polearm: "Polearms", spear: "Spears", axe: "Axes", bow: "Bows",
    crossbow: "Crossbows", elemental: "Elemental Magic", blood: "Blood Magic", fists: "Fists", pickaxe: "Pickaxes", other: "Other",
  } as Record<string, string>,
  slot: {
    helmet: "Helmet", chest: "Chest", legs: "Legs", cape: "Cape", shield: "Shield", utility: "Utility", trinket: "Trinket", other: "Other",
  } as Record<string, string>,
  toolKind: { tool: "Tools", arrow: "Arrows", bolt: "Bolts", ammo: "Other ammo" } as Record<string, string>,
  focus: { health: "Health", stamina: "Stamina", eitr: "Eitr", balanced: "Balanced" } as Record<string, string>,
  effect: { health: "Healing", stamina: "Stamina", eitr: "Eitr", resist: "Resistance", other: "Other" } as Record<string, string>,
  how: {
    drop: "Hunting", pickable: "Picking", mine: "Mining", tree: "Chopping", destructible: "Breaking things", fish: "Fishing",
    chest: "In chests", location: "In dungeons", extract: "Extracting", farm: "Farming", trader: "Buying", craft: "Crafting", convert: "Processing",
  } as Record<string, string>,
  tool: { Hammer: "Hammer", Hoe: "Hoe", Cultivator: "Cultivator", Feaster: "Serving tray" } as Record<string, string>,
  filters: {
    biome: "Biome", station: "Made at", focus: "Focus", effect: "Effect", cls: "Class", dmg: "Main damage", slot: "Slot",
    set: "Set", kind: "Type", tool: "Tool", category: "Category", comfort: "Comfort only", tame: "Tameable only", how: "How to get it",
    usedFor: "Used for", type: "Type", weak: "Weak to", all: "All", anywhere: "Anywhere", noStation: "No station",
    boss: "Bosses", normal: "Creatures", trophy: "Trophies", material: "Materials", noSet: "No set",
  },
  cols: {
    name: "Name", hp: "Health", st: "Stamina", eitr: "Eitr", min: "Lasts", station: "Made at", biome: "Biome",
    dmg: "Damage", cls: "Class", quality: "Max. quality", armor: "Armor", slot: "Slot", set: "Set", effect: "Effect",
    base: "Base", comfort: "Comfort", tool: "Tool", category: "Category", how: "How", usedFor: "Used for",
    health: "Health", weak: "Weak to", biomes: "Biomes", weight: "Weight",
  },
  minutes: (n: number) => `${n} min`,
  level: (n: number) => `level ${n}`,
  detail: {
    back: (tab: string) => `← ${tab}`,
    recipe: "Recipe",
    anyOne: "Any one of these is enough.",
    madeAt: "Made at",
    makes: (n: number) => `Makes ${n}`,
    upgrades: "Upgrades",
    upgradeTo: (q: number) => `Quality ${q}`,
    sources: "Where it comes from",
    usedIn: "Used in",
    summons: "Summons",
    summonsHow: (n: number, altar: string) => (altar ? `offer ${n} at ${altar}` : `offer ${n}`),
    noSources: "The game gives no fixed source for this one.",
    ingSources: "Where each ingredient comes from",
    processes: "What it processes",
    crafts: "Made here",
    upgradeHow: "How to upgrade it",
    upgradeHint: "Each upgrade is built next to the station and raises it one level. Level 1 is the station on its own.",
    unlocks: (n: number) => `Unlocks ${n}`,
    nothingNew: "Nothing new: raises the level of what you already make",
    builtAt: "Built at",
    extendsStation: "Upgrades",
    plusLevel: "+1 level",
    food: "Food",
    duration: "Lasts",
    regen: "Health regen",
    perSecond: (n: number) => `${n}/s`,
    damage: "Damage",
    perLevel: "Per quality level",
    armor: "Armor",
    block: "Block",
    weight: "Weight",
    stack: "Stack",
    comfort: "Comfort",
    chain: "How it's brewed",
    ferment: (min: number) => `${min} min`,
    yields: (n: number) => `×${n}`,
    chance: (p: string) => `${p}`,
    from: {
      craft: "Crafted", convert: "Processed", drop: "Dropped by", gather: "Found", farm: "Grown", trader: "Sold by",
    } as Record<string, string>,
    price: (n: number) => `${n} coins`,
    noBiome: "in dungeons and ruins",
    prev: "Previous",
    next: "Next",
    other: (name: string) => `In Spanish: ${name}`,
  },
  guide: {
    health: "Health",
    weak: "Weak to",
    resist: "Resistant to",
    immune: "Immune to",
    drops: "Drops",
    lives: "Lives in",
    boss: "Boss",
    env: "Weather",
    envFreezing: "Freezing: you need frost resistance (a mead or the right armor) or you will lose health.",
    envCold: "Cold: stay warm near fire, dry and rested.",
    envColdNight: "Cold at night.",
    envWet: "Rain makes you wet: stamina regenerates slower until you dry off.",
    envNone: "No weather effects that hurt you by themselves.",
    creatures: "Creatures",
    enemies: "Enemies of this biome",
    peaceful: "Peaceful creatures",
    resources: "Resources",
    fromCreatures: "Dropped by its creatures",
    loot: "In chests and pots",
    lootHint: "Random loot from the area's chests and pots, not a resource you gather here.",
    plant: "Can be grown here",
    dropsFrom: (names: string) => `from ${names}`,
    foods: "Best food made here",
    gear: "Made with what you find here",
    gearCount: (w: number, a: number, f: number) => `${w} weapons · ${a} armor pieces · ${f} foods`,
    tips: "Hugin says",
    summon: "How to summon",
    summonAt: (n: number, item: string) => `Offer ${n} × ${item} at the altar`,
    summonWhere: "Where to get the offering",
    power: "Forsaken Power",
    cooldown: (s: number) => `Cooldown ${Math.round(s / 60)} min`,
    biome: "Biome",
    open: "Open",
    step: (n: number) => `${n}`,
  },
  // La Crónica: las notas de parche (2026-09-24).
  map: {
    tab: "Map",
    hub: "Your world, by seed",
    seoTitle: "Valheim Interactive Map by Seed (1.0): biomes, bosses, dungeons | Vestigo",
    seoDesc: "Enter your Valheim world seed and explore the full interactive map: biomes, terrain, bosses, dungeons, traders and every location, generated exactly like the game (1.0). Free, in your browser.",
  },
  // El Planificador (2026-09-25): eliges qué fabricar y te dice qué juntar y dónde.
  plan: {
    tab: "Planner",
    hub: "What to gather, and where",
    seoTitle: "Valheim Crafting Planner (1.0): every material and where to find it | Vestigo",
    seoDesc: "Pick what you want to make in Valheim — weapons and armor at any upgrade level, food, meads, buildings, boss offerings — and get every material you need, the biome and creature it comes from, the stations and the total weight. Free, in your browser.",
    title: "Planner",
    lede: "Build your list and get the route: what to gather, how much and in which biome.",
    search: "Search anything you can craft, cook or build",
    all: "All",
    cats: { weapons: "Weapons", armor: "Armor", tools: "Tools", foods: "Food", meads: "Meads", materials: "Materials", building: "Building", bosses: "Bosses" } as Record<string, string>,
    biome: "Biome",
    colItem: "Item", colWhere: "Made at", colBiome: "Biome",
    add: "+ Add",
    inList: (n: number) => `✓ In your list · ${n}`,
    more: (n: number) => `Show ${n} more`,
    noHits: "Nothing you can make matches that.",
    yourList: "Your list",
    clear: "Clear",
    empty: "Your list is empty. Add what you want to make from the table.",
    level: (n: number) => `Level ${n}`,
    less: "One less", plus: "One more", remove: "Remove", qty: "Amount",
    batch: (n: number, made: number) => `Made ${n} at a time: you get ${made}`,
    rawCount: "raw materials",
    biomeCount: "biomes to visit",
    next: "Next: materials →",
    saved: "Your list stays in this browser and in the link.",
    open: (n: number) => `Your list · ${n}`,
    close: "Close",
    routeTitle: "Route",
    back: "← Back to the list",
    weight: "weight",
    trips: (n: number) => `${n} ${n === 1 ? "trip" : "trips"} at 300`,
    smelting: "min of smelting",
    biomes: "biomes",
    breakdown: "Breakdown",
    toTable: "What goes on the table",
    toRaw: "Down to raw",
    forWhat: (names: string) => `For ${names}`,
    atStation: (st: string, n: number) => (n > 1 ? `${st}, ${n} at a time` : st),
    gather: "To gather",
    ready: (a: number, b: number) => `${a} of ${b} ready`,
    have: "I have it",
    stations: "Stations you need",
    stationLevel: (name: string, lv: number) => (lv > 1 ? `${name} · level ${lv}` : name),
    paths: "Paths",
    viaCraft: (st: string) => `craft it (${st})`,
    viaFrom: (name: string) => `from ${name}`,
    viaRaw: "gather it as is",
    anyOf: (name: string) => `${name}: use`,
    copy: "Copy link",
    copied: "Link copied",
    nothing: "Your list is empty.",
    goPick: "Pick what to make",
    how: { drop: "Dropped by", mine: "Mine it", tree: "Chop trees", pickable: "Pick it up", farm: "Farm it", location: "At some locations", extract: "Extract it", fish: "Fish it", destructible: "Break rocks or objects", trader: "Sold by", chest: "In chests" } as Record<string, string>,
    left: (asked: number, made: number) => `you asked for ${asked}, you get ${made}`,
    addBtn: "+ Add to the Planner",
    inPlanner: (n: number) => `✓ In the Planner · ${n}`,
    see: "See the list",
  },
  pat: {
    tab: "Patches",
    title: "The Chronicle",
    lede: "Every official Valheim patch, one edition per version: what's new, what changed and what got fixed, with every item linked to the encyclopedia.",
    seoTab: "Valheim patch notes: every update, item by item | Vestigo",
    seoEdition: (label: string) => `Valheim patch ${label} | Vestigo`,
    seoEditionDesc: (v: string) => `What changed in Valheim ${v}: new content, balance changes and fixes, with every item linked to its recipe and stats.`,
    loading: "Unrolling the scroll…",
    notFound: "There is no edition for that version.",
    update: "Update",
    patch: "Patch",
    official: "Read on Steam",
    letter: "From Iron Gate",
    readMore: "Read the whole letter",
    filter: "Filter by type",
    all: "All",
    new: "New",
    mid: "Changes",
    fix: "Fixes",
    touches: "What it touches",
    hotfixes: "Hotfixes",
    archive: "Archive",
    noSpanish: "",
    prev: "Older",
    next: "Newer",
    latest: "Latest edition",
  },
};

const ES: typeof EN = {
  seo: {
    home: {
      title: "Valheim en español: recetas, comidas, hidromieles, armas y jefes | Vestigo",
      description: "Todas las recetas, comidas, hidromieles, armas, armaduras, construcciones y criaturas de Valheim 1.0, con los nombres oficiales en español e inglés y de dónde sale cada cosa.",
    },
    tab: (tab) => `${tab} de Valheim: la lista completa con filtros | Vestigo`,
    detail: (name, tab) => `${name} — ${tab} de Valheim | Vestigo`,
    detailDesc: (name) => `${name} en Valheim: receta, estadísticas, de dónde sale y para qué sirve, sacado de los archivos del juego.`,
  },
  title: "Valheim",
  lede: "Todo lo que el juego te deja fabricar, comer, construir y cazar, con los nombres oficiales y de dónde sale cada cosa.",
  loading: "Abriendo el cofre…",
  notFound: "Eso no está en la enciclopedia.",
  search: "Buscar en todo…",
  searchTab: "Buscar en esta pestaña…",
  noResults: "No hay nada con ese nombre.",
  clear: "Limpiar filtros",
  filtersTitle: "Filtros",
  count: (n, total) => (n === total ? `${total}` : `${n} de ${total}`),
  fromGame: "Nombres, números, íconos e ilustraciones de biomas salen de los archivos del juego (Valheim 1.0), revisados contra la Valheim Wiki. Valheim es un juego de Iron Gate; Vestigo no está afiliado.",
  photoBy: (a: string | null) => (a ? `Foto: ${a} / Valheim Wiki` : "Foto: Valheim Wiki"),
  places: "Mazmorras y lugares",
  inhabitants: "Quién vive ahí",
  placeLoot: "En sus cofres",
  variant: "Variante",
  more: {
    tame: "Domesticación", tameTime: (m) => `Tarda unos ${m} min, siempre alimentada y lejos de peleas`, fed: (m) => `La comida le dura ${m} min`,
    eats: "Come", startsTamed: "Ya es mansa: no hace falta domesticarla.", saddle: "Se puede montar con", commandable: "Te sigue y obedece cuando la llamas.",
    breed: "Cría", breedMax: (n) => `Se reproduce mientras haya menos de ${n} de su especie cerca`,
    breedLove: (n) => `Tiene que comer ${n} veces para quedar preñada`, breedTime: (s) => `Preñez: ${s} s`, offspring: "Cría",
    spawns: "Cuándo y dónde aparece", day: "De día", night: "De noche", dayNight: "De día y de noche", after: "después de derrotar a",
    group: (a, b) => (a === b ? (a > 1 ? `en grupos de ${a}` : "sola") : `en grupos de ${a} a ${b}`),
    forestIn: "en el bosque", forestOut: "fuera del bosque", ocean: "en el mar", altitude: (m) => `a más de ${m} m de altura`, weather: "clima",
    events: "Ataques en los que aparece", biomeEvents: "Ataques de enemigos del bioma", eventAfter: "desde", eventUntil: "hasta",
    attacks: "Ataques", tips: "Consejos", cooldown: (s) => `cada ${s} s`,
    effects: "Efectos", setBonus: (n) => (n ? `Bono de set (${n} piezas)` : "Bono de set"), setPieces: "Las otras piezas del set",
    equip: "Al equiparlo", consume: "Al tomarlo", resists: "Resistencias", move: (p) => `${p > 0 ? "+" : ""}${p}% velocidad al moverte`,
    mod: { resistant: "Resistente", weak: "Débil", immune: "Inmune", veryResistant: "Muy resistente", veryWeak: "Muy débil",
      slightlyResistant: "Algo resistente", slightlyWeak: "Algo débil" },
    stat: {
      healthUpFront: (v) => `+${v} de vida al instante`, staminaUpFront: (v) => `+${v} de aguante al instante`, eitrUpFront: (v) => `+${v} de eitr al instante`,
      healthOverTime: (v) => `+${v} de vida con el tiempo`, staminaOverTime: (v) => `+${v} de aguante con el tiempo`, eitrOverTime: (v) => `+${v} de eitr con el tiempo`,
      healthRegenMultiplier: (v) => `Regeneración de vida ×${v}`, staminaRegenMultiplier: (v) => `Regeneración de aguante ×${v}`, eitrRegenMultiplier: (v) => `Regeneración de eitr ×${v}`,
      addMaxCarryWeight: (v) => `+${v} de peso que puedes cargar`, speedModifier: (v) => `${pct(v)} de velocidad al moverte`, swimSpeedModifier: (v) => `${pct(v)} de velocidad al nadar`,
      runStaminaDrainModifier: (v) => `${pct(v)} de aguante al correr`, jumpStaminaUseModifier: (v) => `${pct(v)} de aguante al saltar`,
      attackStaminaUseModifier: (v) => `${pct(v)} de aguante al atacar`, blockStaminaUseModifier: (v) => `${pct(v)} de aguante al bloquear`,
      dodgeStaminaUseModifier: (v) => `${pct(v)} de aguante al esquivar`, swimStaminaUseModifier: (v) => `${pct(v)} de aguante al nadar`,
      sneakStaminaUseModifier: (v) => `${pct(v)} de aguante al agacharte`, runStaminaUseModifier: (v) => `${pct(v)} de aguante al correr`,
      homeItemStaminaUseModifier: (v) => `${pct(v)} de aguante con herramientas`, noiseModifier: (v) => `${pct(v)} de ruido`,
      stealthModifier: (v) => `${pct(v)} de sigilo`, fallDamageModifier: (v) => `${pct(v)} de daño por caída`, maxMaxFallSpeed: () => "Caída lenta",
      addArmor: (v) => `+${v} de armadura`, staggerModifier: (v) => `${pct(v)} de aturdimiento`, timedBlockBonus: (v) => `${pct(v)} de bonificación al parar`,
      adrenalineModifier: (v) => `${pct(v)} de adrenalina`, windRunStaminaModifier: (v) => `${pct(v)} de aguante corriendo con el viento`,
      damageModifier: (v) => `Daño ×${v}`, ttl: (v) => `Dura ${Math.round(v / 60) >= 1 ? `${Math.round(v / 60)} min` : `${v} s`}`,
    },
    skill: (name, v) => `${v > 0 ? "+" : ""}${v} en ${name}`,
    damagePct: (type, v) => `${pct(v)} de daño ${type.toLowerCase()}`,
    skills: { 1: "Espadas", 2: "Cuchillos", 3: "Mazas", 4: "Piquetes", 5: "Lanzas", 6: "Bloqueo", 7: "Hachas", 8: "Arcos", 9: "Magia elemental",
      10: "Magia de sangre", 11: "Desarmado", 12: "Picos", 13: "Talar", 14: "Ballestas", 100: "Saltar", 101: "Sigilo", 102: "Correr",
      103: "Nadar", 104: "Pesca", 105: "Cocina", 106: "Agricultura", 107: "Artesanía", 110: "Montar" },
    env: { Rain: "lluvia", LightRain: "llovizna", ThunderStorm: "tormenta", Misty: "niebla" },
  },
  placeResources: "Qué se encuentra ahí",
  foundIn: "Dónde aparece",
  allBiomes: "Todos",
  wikiCredit: "Lugares, hábitats y fotos de criaturas y lugares:",
  wikiLicense: "bajo licencia CC BY-SA 3.0 (el autor de cada foto aparece al pasar el cursor).",
  tabs: {
    foods: "Comidas", meads: "Hidromieles", weapons: "Armas", armor: "Armaduras", tools: "Herramientas",
    building: "Construcción", materials: "Materiales", creatures: "Criaturas", biomes: "Biomas", places: "Lugares", bosses: "Jefes",
  },
  tabLede: {
    foods: "Todo lo que se come: cuánto da, cuánto dura y cómo se cocina.",
    meads: "De la malta en el caldero de aguamiel al fermentador: qué lleva cada hidromiel y qué hace.",
    weapons: "Cada arma, su daño y lo que cuesta cada mejora.",
    armor: "Cascos, pecheras, grebas, capas, escudos y abalorios, con su armadura y su set.",
    tools: "Herramientas, flechas, virotes y el resto de la munición.",
    building: "Todo lo que ponen el martillo, la azada, el cultivador y la bandeja, y lo que cuesta.",
    materials: "Cada material y trofeo, de dónde sale y para qué sirve.",
    creatures: "Cada criatura: vida, qué le hace daño, qué suelta y dónde vive.",
    biomes: "Los nueve biomas en orden: qué vive ahí, qué encuentras, qué llevar y quién manda.",
    places: "Mazmorras, ruinas y lugares de cada bioma: quién vive adentro y qué se encuentra ahí.",
    bosses: "Los Desterrados: cómo invocarlos, qué les pega y el poder que dejan.",
  },
  biomes: {
    meadows: "Praderas", blackforest: "Bosque negro", swamp: "Pantano", mountain: "Montaña", plains: "Llanuras",
    ocean: "Océano", mistlands: "Tierras Nubladas", ashlands: "Tierra de Ceniza", deepnorth: "Norte profundo",
  },
  damage: {
    blunt: "Contundente", slash: "Tajante", pierce: "Perforante", fire: "Fuego", frost: "Escarcha", lightning: "Rayo",
    poison: "Veneno", spirit: "Espíritu", chop: "Cortante", pickaxe: "Pico", damage: "Daño",
  },
  weaponCls: {
    sword: "Espadas", knife: "Cuchillos", club: "Garrotes", polearm: "Piquetes", spear: "Lanzas", axe: "Hachas", bow: "Arcos",
    crossbow: "Ballestas", elemental: "Magia elemental", blood: "Magia de sangre", fists: "Desarmado", pickaxe: "Picos", other: "Otras",
  },
  slot: {
    helmet: "Casco", chest: "Pechera", legs: "Grebas", cape: "Capa", shield: "Escudo", utility: "Utilidad", trinket: "Abalorio", other: "Otro",
  },
  toolKind: { tool: "Herramientas", arrow: "Flechas", bolt: "Virotes", ammo: "Otra munición" },
  focus: { health: "Vida", stamina: "Aguante", eitr: "Eitr", balanced: "Equilibrada" },
  effect: { health: "Curación", stamina: "Aguante", eitr: "Eitr", resist: "Resistencia", other: "Otros" },
  how: {
    drop: "Cazando", pickable: "Recogiendo", mine: "Minando", tree: "Talando", destructible: "Rompiendo objetos", fish: "Pescando",
    chest: "En cofres", location: "En mazmorras", extract: "Extrayendo", farm: "Cultivando", trader: "Comprando", craft: "Fabricando", convert: "Procesando",
  },
  tool: { Hammer: "Martillo", Hoe: "Azada", Cultivator: "Cultivador", Feaster: "Bandeja" },
  filters: {
    biome: "Bioma", station: "Dónde se hace", focus: "Enfoque", effect: "Efecto", cls: "Clase", dmg: "Daño principal", slot: "Parte",
    set: "Set", kind: "Tipo", tool: "Herramienta", category: "Categoría", comfort: "Sólo con confort", tame: "Sólo domesticables", how: "Cómo se consigue",
    usedFor: "Se usa en", type: "Tipo", weak: "Débil a", all: "Todos", anywhere: "Todas", noStation: "Sin estación",
    boss: "Jefes", normal: "Criaturas", trophy: "Trofeos", material: "Materiales", noSet: "Sin set",
  },
  cols: {
    name: "Nombre", hp: "Vida", st: "Aguante", eitr: "Eitr", min: "Dura", station: "Dónde se hace", biome: "Bioma",
    dmg: "Daño", cls: "Clase", quality: "Calidad máx.", armor: "Armadura", slot: "Parte", set: "Set", effect: "Efecto",
    base: "Malta", comfort: "Confort", tool: "Herramienta", category: "Categoría", how: "Cómo", usedFor: "Se usa en",
    health: "Vida", weak: "Débil a", biomes: "Biomas", weight: "Peso",
  },
  minutes: (n) => `${n} min`,
  level: (n) => `nivel ${n}`,
  detail: {
    back: (tab) => `← ${tab}`,
    recipe: "Receta",
    anyOne: "Alcanza con uno cualquiera de estos.",
    madeAt: "Se hace en",
    makes: (n) => `Hace ${n}`,
    upgrades: "Mejoras",
    upgradeTo: (q) => `Calidad ${q}`,
    sources: "De dónde sale",
    usedIn: "Se usa en",
    summons: "Invoca a",
    summonsHow: (n, altar) => (altar ? `se ofrecen ${n} en ${altar}` : `se ofrecen ${n}`),
    noSources: "El juego no le da una fuente fija.",
    ingSources: "De dónde sale cada ingrediente",
    processes: "Qué procesa",
    crafts: "Qué se hace acá",
    upgradeHow: "Cómo se mejora",
    upgradeHint: "Cada mejora se construye cerca de la estación y le sube un nivel. El nivel 1 es la estación sola.",
    unlocks: (n: number) => `Desbloquea ${n}`,
    nothingNew: "Nada nuevo: sube el nivel de lo que ya haces",
    builtAt: "Se hace en",
    extendsStation: "Mejora",
    plusLevel: "+1 nivel",
    food: "Comida",
    duration: "Dura",
    regen: "Regeneración de vida",
    perSecond: (n) => `${n}/s`,
    damage: "Daño",
    perLevel: "Por nivel de calidad",
    armor: "Armadura",
    block: "Bloqueo",
    weight: "Peso",
    stack: "Pila",
    comfort: "Confort",
    chain: "Cómo se prepara",
    ferment: (min) => `${min} min`,
    yields: (n) => `×${n}`,
    chance: (p) => `${p}`,
    from: {
      craft: "Se fabrica", convert: "Se procesa", drop: "Lo suelta", gather: "Se encuentra", farm: "Se cultiva", trader: "Lo vende",
    },
    price: (n) => `${n} monedas`,
    noBiome: "en mazmorras y ruinas",
    prev: "Anterior",
    next: "Siguiente",
    other: (name) => `En inglés: ${name}`,
  },
  guide: {
    health: "Vida",
    weak: "Débil a",
    resist: "Resiste",
    immune: "Inmune a",
    drops: "Suelta",
    lives: "Vive en",
    boss: "Jefe",
    env: "Clima",
    envFreezing: "Congelante: necesitas resistencia a la escarcha (una hidromiel o la armadura adecuada) o vas a perder vida.",
    envCold: "Frío: mantente cerca del fuego, seco y descansado.",
    envColdNight: "De noche hace frío.",
    envWet: "La lluvia te moja: el aguante se recupera más lento hasta que te seques.",
    envNone: "Sin clima que te lastime por sí solo.",
    creatures: "Criaturas",
    enemies: "Enemigos del bioma",
    peaceful: "Criaturas pacíficas",
    resources: "Recursos",
    fromCreatures: "Lo que sueltan sus criaturas",
    loot: "En cofres y vasijas",
    lootHint: "Botín al azar de los cofres y vasijas de la zona, no un recurso que se junte acá.",
    plant: "Se puede cultivar acá",
    dropsFrom: (names: string) => `de ${names}`,
    foods: "Las mejores comidas de aquí",
    gear: "Hecho con lo que encuentras aquí",
    gearCount: (w, a, f) => `${w} armas · ${a} piezas de armadura · ${f} comidas`,
    tips: "Hugin dice",
    summon: "Cómo invocarlo",
    summonAt: (n, item) => `Ofrece ${n} × ${item} en el altar`,
    summonWhere: "Dónde se consigue la ofrenda",
    power: "Poder de los Desterrados",
    cooldown: (s) => `Recarga de ${Math.round(s / 60)} min`,
    biome: "Bioma",
    open: "Abrir",
    step: (n) => `${n}`,
  },
  map: {
    tab: "Mapa",
    hub: "Tu mundo, por semilla",
    seoTitle: "Mapa interactivo de Valheim por semilla (1.0): biomas, jefes y mazmorras | Vestigo",
    seoDesc: "Escribe la semilla de tu mundo de Valheim y explora el mapa interactivo completo: biomas, relieve, jefes, mazmorras, comerciantes y todos los lugares, generados exactamente como en el juego (1.0). Gratis, en tu navegador.",
  },
  plan: {
    tab: "Planificador",
    hub: "Qué juntar y dónde",
    seoTitle: "Planificador de Valheim (1.0): todos los materiales y dónde conseguirlos | Vestigo",
    seoDesc: "Elige lo que quieres fabricar en Valheim — armas y armaduras en cualquier nivel, comidas, hidromieles, construcciones, ofrendas de jefes — y obtén cada material que necesitas, el bioma y la criatura de donde sale, las estaciones y el peso total. Gratis, en tu navegador.",
    title: "Planificador",
    lede: "Arma tu lista y te damos la hoja de ruta: qué juntar, cuánto y en qué bioma.",
    search: "Busca cualquier cosa que se fabrique, se cocine o se construya",
    all: "Todo",
    cats: { weapons: "Armas", armor: "Armaduras", tools: "Herramientas", foods: "Comidas", meads: "Hidromieles", materials: "Materiales", building: "Construcción", bosses: "Jefes" },
    biome: "Bioma",
    colItem: "Objeto", colWhere: "Se hace en", colBiome: "Bioma",
    add: "+ Agregar",
    inList: (n) => `✓ En la lista · ${n}`,
    more: (n) => `Ver ${n} más`,
    noHits: "No hay nada que se fabrique con ese nombre.",
    yourList: "Tu lista",
    clear: "Vaciar",
    empty: "Tu lista está vacía. Agrega desde la tabla lo que quieres fabricar.",
    level: (n) => `Nivel ${n}`,
    less: "Uno menos", plus: "Uno más", remove: "Quitar", qty: "Cantidad",
    batch: (n, made) => `Salen de a ${n}: te quedan ${made}`,
    rawCount: "materiales crudos",
    biomeCount: "biomas por recorrer",
    next: "Siguiente: materiales →",
    saved: "La lista queda guardada en este navegador y en el enlace.",
    open: (n) => `Tu lista · ${n}`,
    close: "Cerrar",
    routeTitle: "Hoja de ruta",
    back: "← Volver a la lista",
    weight: "de peso",
    trips: (n) => `${n} ${n === 1 ? "viaje" : "viajes"} con 300 de carga`,
    smelting: "min de fundición",
    biomes: "biomas",
    breakdown: "Desglose",
    toTable: "Lo que va a la mesa",
    toRaw: "Hasta lo crudo",
    forWhat: (names) => `Para ${names}`,
    atStation: (st, n) => (n > 1 ? `${st}, de a ${n}` : st),
    gather: "Para juntar",
    ready: (a, b) => `${a} de ${b} listos`,
    have: "Ya lo tengo",
    stations: "Estaciones que necesitas",
    stationLevel: (name, lv) => (lv > 1 ? `${name} · nivel ${lv}` : name),
    paths: "Caminos",
    viaCraft: (st) => `fabricarlo (${st})`,
    viaFrom: (name) => `de ${name}`,
    viaRaw: "juntarlo tal cual",
    anyOf: (name) => `${name}: usar`,
    copy: "Copiar enlace",
    copied: "Enlace copiado",
    nothing: "Tu lista está vacía.",
    goPick: "Elegir qué fabricar",
    how: { drop: "Lo suelta", mine: "Se mina", tree: "Talando árboles", pickable: "Se recoge del suelo", farm: "Se cultiva", location: "En ciertos lugares", extract: "Se extrae", fish: "Se pesca", destructible: "Rompiendo rocas u objetos", trader: "Lo vende", chest: "En cofres" },
    left: (asked, made) => `pediste ${asked}, salen ${made}`,
    addBtn: "+ Agregar al Planificador",
    inPlanner: (n) => `✓ En el Planificador · ${n}`,
    see: "Ver la lista",
  },
  pat: {
    tab: "Parches",
    title: "La Crónica",
    lede: "Todos los parches oficiales de Valheim, una edición por versión: lo nuevo, lo que cambió y lo que se arregló, con cada objeto enlazado a la enciclopedia.",
    seoTab: "Parches de Valheim: todas las actualizaciones, objeto por objeto | Vestigo",
    seoEdition: (label) => `Valheim · parche ${label} | Vestigo`,
    seoEditionDesc: (v) => `Qué cambió en Valheim ${v}: contenido nuevo, cambios de equilibrio y arreglos, con cada objeto enlazado a su receta y sus stats.`,
    loading: "Desenrollando el pergamino…",
    notFound: "No hay una edición para esa versión.",
    update: "Actualización",
    patch: "Parche",
    official: "Leer en Steam",
    letter: "Palabras de Iron Gate",
    readMore: "Leer la carta completa",
    filter: "Filtrar por tipo",
    all: "Todo",
    new: "Novedades",
    mid: "Cambios",
    fix: "Arreglos",
    touches: "Lo que toca",
    hotfixes: "Hotfixes",
    archive: "Hemeroteca",
    noSpanish: "Iron Gate publica las notas de parche sólo en inglés y esta edición todavía no está traducida: va en el original.",
    prev: "Anterior",
    next: "Siguiente",
    latest: "Última edición",
  },
};

export type ValheimCopy = typeof EN;
/** Un modificador del juego como porcentaje con signo: 0.15 → "+15%". */
const pct = (v: number) => `${v > 0 ? "+" : ""}${Math.round(v * 100)}%`;

export const VALHEIM_COPY: Record<"en" | "es", ValheimCopy> = { en: EN, es: ES };
export const useValheimCopy = () => VALHEIM_COPY[useLang().lang];
